### ISSUE TITLE
Pre-parsed stdlib

### ISSUE THREAD

**Issue by sbarzowski** [google/go-jsonnet#100]
@mqliang wrote in #89:
> It would be very interesting if we can dump ast as go source files, then we can dump ast of stdlib as go source code, and embed it into vm, thus avoid parsing stdlib every time. Any idea?

I think we should look into it. It sound quite easy.

**Comment by mqliang** [comment]
I tried to dump ast using go-spew (https://github.com/davecgh/go-spew), it's practicable: about 7w line source code is generated. 

The problem is: we need fork go-spew and modify its source code to make the generated files meet go's syntax.

**Comment by sbarzowski** [comment]
My feeling is that the easiest and most maintainable way would be to do it by hand, i.e. have a function that does a type switch over ast nodes and formats each of them into a go source code representation. There are just ~30 AST node types IIRC. This will give us full control over the output and let us specially handle location information, aliased nodes and other complex cases. I think that with some helper functions the boilerplate could be minimal.

**Comment by mqliang** [comment]
utter(github.com/kortschak/utter) works. 

The only problem is: we need make ALL fields of AST node as public, then the dumped source code can be put in any package. Otherwise, we must put the source code in the "ast" package.

**Comment by mqliang** [comment]
https://github.com/google/go-jsonnet/issues/82 will also benefit from this.
