### ISSUE TITLE
Weird std.exp(something_big) on some platforms.

### ISSUE THREAD

**Issue by sbarzowski** [google/go-jsonnet#132]
We're affected by this: https://github.com/golang/go/issues/14932

BTW it seems it is non-trivial to have exactly the same values of numeric functions on all platforms - https://github.com/golang/go/issues/20319.

**Comment by sparkprime** [comment]
There's a case for removing (a)sin, (a)cos, (a)tan, sqrt, exp, log, pow for precisely this reason.

We can keep floor, ceil, exponent, mantissa as they are straightforward and should be the same everywhere.

We could provide an integer version of log -- one that returns ceil(log(floor(a), floor(b))).  We can provide an integer version of pow via a ** operator.

**Comment by sbarzowski** [comment]
I don't think there is any action is going to be needed here, so I'll close this. We have some tests which try to ensure that floating point operations behave reasonably in general.
