### ISSUE TITLE
Cannot return RuntimeError from native function

### ISSUE THREAD

**Issue by camh-** [google/go-jsonnet#164]
While the RuntimeError type is exported, there does not seem to be an exported way to construct a RuntimeError or an exported way to populate the StackTrace ([]TraceFrame) from.

It would be useful to be able to have an exported variant of the get* functions in evaluator.go that return Go types (e.g. string instead of valueString) and a RuntimeError. However, just being able to get the stacktrace and exporting makeRuntimeError would be sufficient.

Returning other error types from a native function results in an "INTERNAL ERROR" error message, requesting that the user file a bug. The lack of a stack trace in the error message can make it difficult to know what caused the error.

**Comment by camh-** [comment]
Pinging @sbarzowski as requested.

**Comment by sparkprime** [comment]
Specifically, camh wants to return an error from a NativeCallback and there's only the regular error return there.  I'm not sure if it even has support for RuntimeError or whether it just treats everything as an internal error.

**Comment by sbarzowski** [comment]
Ah. It's a mistake, thanks for finding it. The idea was to always wrap this error as a runtime error. (And if you really want to crash with an internal error you can just panic  - this will also cause a stack trace to be included).

Here's a pull request which fixes that: #165 (no tests at the moment, I'll try to add some later).

**Comment by camh-** [comment]
LGTM. I wrote a test if you want it, here: https://github.com/camh-/go-jsonnet/commit/4ff0363469567bfdc93207fa9d1fb4fcb0930fc0

**Comment by sbarzowski** [comment]
@camh- Cool! Of course I want it :-). Please send a pull request (directly to google/go-jsonnet).

**Comment by camh-** [comment]
Pull request #166 sent. It is based on master so the tests will be failing until #165 is merged.
