### ISSUE TITLE
RUNTIME ERROR: Couldn't manifest function in JSON output.

### ISSUE THREAD

**Issue by PureWhiteWu** [google/go-jsonnet#168]
I found this in code:
```
case *valueFunction:
		return nil, makeRuntimeError("Couldn't manifest function in JSON output.", i.getCurrentStackTrace(trace))
```
and my input is something like this:
```
local a = import "../../../applib/a.libsonnet";
local b = import "../../../applib/b.libsonnet";

function(config={})
  local overall_config = default_config + config;
  (if a.match(overall_config) then
    {
      ...
    }
  else
    {
      ...
    }) + {
    ...
  }
```
And i get this:
```
RUNTIME ERROR: Couldn't manifest function in JSON output.
	During manifestation
```
How can i resolve this?
Thanks!

**Comment by sparkprime** [comment]
You probably have a function buried in those objects somewhere.  The stacktrace should help you locate it, if not, that's a bug in itself.

**Comment by sbarzowski** [comment]
Hello @PureWhiteWu,

The result of this program is a function (@sparkprime: it's not buried, the whole thing is a function). When you execute this file jsonnet wants to print the result - but it can't print functions.

If you intended this file to be a library, the idiomatic way is to wrap it in an object:
`
{
    my_func_name(config={}):: 
        local ....
}
`
You can also run the function with an argument directly from commandline using top level arguments, ex.
`jsonnet --tla-code 'config={config_param: 42} your_file.jsonnet'

**Comment by sparkprime** [comment]
If it's a function and it can be executed without arguments, you don't need to give top level arguments

```
dcunnin@dcunnin7:~$ jsonnet -e 'function(config={})config'
{ }
```

**Comment by sbarzowski** [comment]
Oh, so there is a difference between Go and C++ versions. In Go it still tries to manifest this function. The C++ behavior makes more sense probably. So we gotta fix it, I guess.

For now the workaround is to provide at least one argument, through `--tla-str`/`--tla-code`.

**Comment by PureWhiteWu** [comment]
@sbarzowski thanks very much! Can you notify me when this is fixed?
I'm not quite familiar with compilation principle so maybe not able to send prs...

**Comment by sparkprime** [comment]
Ah I remember us discussing this but I didn't realise there was a divergence.  Also we should have a test for this case in the test_cmd suite.

```
dcunnin@casterly:~$ go-workspace/bin/jsonnet -e 'function(config={})config'
RUNTIME ERROR: Couldn't manifest function in JSON output.
        During manifestation
```

**Comment by sparkprime** [comment]
Test is here: https://github.com/google/jsonnet/pull/428

**Comment by sbarzowski** [comment]
@PureWhiteWu It is fixed on master now.

**Comment by PureWhiteWu** [comment]
@sbarzowski okay, thanks! I will try it!

**Comment by PureWhiteWu** [comment]
It works fine! thanks!
