### ISSUE TITLE
[incompatible go version] unexpected = in type declaration

### ISSUE THREAD

**Issue by windwizard** [google/go-jsonnet#172]
My golang version is 1.7.6.
when i tried to build the binary, i got 
go-jsonnet/vm.go:91: syntax error: unexpected = in type declaration

It seems type alias was introduced in [go 1.9](https://golang.org/doc/go1.9) , while  README says this code work on GO 1.6 and above

**Comment by sbarzowski** [comment]
Right. We're using go 1.9 on CI, so we missed that. We don't even need a type alias there.

I fixed it in this change: #173

To avoid such issues in the future we need: #174

**Comment by windwizard** [comment]
@sbarzowski Thank you for the quick fix!!

As you will continue to support older golang version, i sent another pr to fix one more incompatible in https://github.com/google/go-jsonnet/pull/175

**Comment by sparkprime** [comment]
Thanks, I'll close this unless there are any more

**Comment by ne-vlezay80** [comment]
cfghj

**Comment by ne-vlezay80** [comment]
У меня тоже самое
