### ISSUE TITLE
ksonnet 0.8.0 crashes when evaluating component

### ISSUE THREAD

**Issue by redbaron** [google/go-jsonnet#179]
ksonnet crashes inside go-jsonnet: https://gist.github.com/redbaron/8fa492f88923e5f5d9b663941eb153d6

I don't have minimal test case right now, but crash occurs when my local component end with following:

```
local ingress = if (params + { ingress+: { enabled: if "enabled" in super then super.enabled else false }}).ingress.enabled then lib.ingress(svc) else {};
deploy.render([deployment, svc, ingress])
```

**Comment by sparkprime** [comment]
Fixed by #180
