### ISSUE TITLE
Test cmdline handling edge cases

### ISSUE THREAD

**Issue by marcelocantos** [google/go-jsonnet#200]
While working on #380, I accidentally broke the command-line processing logic because golint produced a spurious recommendation:

![image](https://user-images.githubusercontent.com/215143/36689254-fd9c45b6-1b82-11e8-8887-31883867ad9a.png)

```bash
$ golint -min_confidence 0 ./jsonnet
jsonnet/cmd.go:324:11: if block ends with a return statement, so drop this else and outdent its block
```

Automated tests didn't pick this up.

Need more cmdline tests.

**Comment by marcelocantos** [comment]
https://github.com/golang/lint/issues/382

**Comment by sbarzowski** [comment]
Just to be clear, have you run "./tests.sh"? `go test -v ./...` doesn't run tests from the C++ test suite.

BTW This seems to be the right place to add commandline tests: https://github.com/google/jsonnet/blob/master/test_cmd/run_cmd_tests.sh

BTW2 Something like `jsonnet -S -S -S -S -e '"blah"'` should catch it, right?

**Comment by marcelocantos** [comment]
I tried it just now and I can't figure it out:

```bash
$ ./tests.sh
./tests.sh: line 8: tests_path.source: No such file or directory
```

It wants a `tests.source`, presumably to set the `TESTS_PATH`, which it will then cd to and run another `tests.sh`. But there's no other `tests.sh` in the code base.

**Comment by sbarzowski** [comment]
Ah, right, it's described nowhere in the README and it's a tad bit hacky.

You need to create `tests.source` containing `export TESTS_PATH="/path/to/cpp-jsonnet/`

**Comment by sparkprime** [comment]
We could also git submodule cpp jsonnet into go-jsonnet, but people seem to hate that

**Comment by marcelocantos** [comment]
I don't hate submodules. It would be much cleaner from a testing perspective, and could even be added to CI. It would be super easy to add a line to tests.sh to ensure the submodule is up to date before running the tests, thus almost no one would need to deal with it explicitly.

**Comment by marcelocantos** [comment]
#202 adds the google/jsonnet as a submodule.

**Comment by marcelocantos** [comment]
Assuming the C++ tests cover enough cmdline cases, I guess not. I confirmed that the problem that triggered this issue (golint recommending spurious else-removal) is covered.
