### ISSUE TITLE
Update .travis.yml to Go 1.10

### ISSUE THREAD

**Issue by marcelocantos** [google/go-jsonnet#203]
Should the travis-ci build be moved from Go 1.8.x to 1.10.x (or 1.9.x and 1.10.x added)?

**Comment by sbarzowski** [comment]
We already have 1.10 if I understand our setup correctly.

We test go-jsonnet against three versions of Go:
- Go 1.8 - oldest that we support.
- Go 1.x (at the moment 1.10) - latest release
- Go tip (current master)

**Comment by marcelocantos** [comment]
Ah, of course. Didn't click that 1.x would be the latest release.
