### ISSUE TITLE
Reuse C++ Jsonnet's std.jsonnet

### ISSUE THREAD

**Issue by marcelocantos** [google/go-jsonnet#205]
#202 Brings the C++ Jsonnet into go-jsonnet as a submodule. Consequently, its version of std.jsonnet is readily available at a known path.

Should `cpp-jsonnet/stdlib/std.jsonnet` be made the common source of truth for the standard library?

**Comment by marcelocantos** [comment]
The main caveat with this approach is that submodules don't update by default when using git's cli (though I believe most GUI-based git clients do). This carries a small risk that a developer forgets to `git submodule update` and spends a good half hour confused and frustrated. On the plus side, it wouldn't be an issue with the standard instructions in the README, since go get automatically fetches submodules (https://github.com/golang/go/commit/a444da033c0bc1fa5fb1973bd6d0c131ec3c1ccd).

**Comment by sparkprime** [comment]
If this can work smoothly with existing tooling, we should definitely do it.

**Comment by sbarzowski** [comment]
Fixed by #269
