### ISSUE TITLE
Preserving cache between evaluate calls

### ISSUE THREAD

**Issue by sbarzowski** [google/go-jsonnet#208]
@Quentin-M says:
> It seems that the VM is very stateless at this point, but it would be very beneficial to have the imported libraries cached across multiple evaluate calls.

(source & more info: #192)

**Comment by Quentin-M** [comment]
I've just noticed https://github.com/google/go-jsonnet/pull/225, thanks for that.

The biggest time [consumer](https://github.com/google/go-jsonnet/pull/192#issuecomment-370879013) to us, as we compile several directories/files, is the fact that even though we use one instance only of the go-jsonnet VM, with `vm.Importer(&jsonnet.FileImporter{libraryPaths})`, each `vm.EvaluateSnippet` parses/analyzes the imported libraries.

**Comment by Quentin-M** [comment]
With very little code change, I was able to keep an interpreter around for a VM, and we indeed see a tremendous speed increase. Now, we also want to keep the ability to have different ext for each evaluate calls, making sure to refresh the interpreter's extVars with a new call to `prepareExtVars` helped quite a bit, but I am now looking at what looks like re-use of cached data that should have been updated upon the ext change (e.g. evaluating the same jsonnet file twice, with different env: gets the second file rendered with the first ext' values).

**Comment by Quentin-M** [comment]
Actually, the second half of the problem, which is what I am currently facing as mentioned above, seems very related to https://github.com/google/go-jsonnet/issues/126.

**Comment by Quentin-M** [comment]
Trying to understand the code, looking at the content of `cache.codeCache` between each evaluation, and how it works in [ImportCode](https://github.com/google/go-jsonnet/blob/2973e24152b2f0721311a1f3018ae7246d23d103/imports.go#L127-L142).

```
test.libsonnet --> &jsonnet.cachedThunk{env:(*jsonnet.environment)(0xc42041c6c0), body:(*ast.Local)(0xc420391880), content:jsonnet.value(nil), err:error(nil)}

test.libsonnet --> &jsonnet.cachedThunk{env:(*jsonnet.environment)(nil), body:(*ast.Local)(0xc420391880), content:(*jsonnet.valueSimpleObject)(0xc42016e100), err:error(nil)}
```

It seems to me that because `pv` in the cache is a pointer, and because `i.evaluatePV(pv, trace)` is called on the first evaluation, the `pv` in the cache becomes evaluated, therefore caching the rendered code with the specific env. The second call then just grabs this, rather than getting the AST and re-evaluating it with the new env.

**Comment by Quentin-M** [comment]
Hi @sbarzowski!

Do you think this is a doable / worthy issue to tackle?

**Comment by sbarzowski** [comment]
Yes, I think it's something very doable and I would like to see this happen eventually. I have it somewhere in my own backlog, but there's a lot of other stuff to do as well 😄. Help will be very much appreciated!

Below are my thoughts on how I would go about it. I hope this helps, but this is not necessarily the best way and I'll be happy to see any other solutions.

Currently `ImportCache` is created in `buildInterpreter` in `interpreter.go`. At the moment a new interpreter object is created every time a snippet is evaluated. This needs to change to address this issue. I think the easiest way to handle it is move the building of interpreter from the following functions to `VM`:
https://github.com/google/go-jsonnet/blob/master/interpreter.go#L1198
https://github.com/google/go-jsonnet/blob/master/interpreter.go#L1225
https://github.com/google/go-jsonnet/blob/master/interpreter.go#L1243

There is more than one way to add building of interpreter to `VM` (https://github.com/google/go-jsonnet/blob/master/vm.go#L33). The most straightforward way is to have a private field `i *interpreter` which is filled on first `evaluate`. This however comes with a problem - what if someone then changes extVars - all the calls to `std.extVar('whatever')` are already cached in the imported files. This could be alleviated by "freezing" the properties which can no longer be changed (extVars, importer, something more?) - erroring out if someone tries to change them and interpreter is already there.  But this still has some potential to break existing users (those who change extVars after first evaluation).

The best alternative I can think of right now is not to add any field to VM, but add a method to it which returns a wrapped interpreter, which can be used multiple times (with the same interpreter, so preserving cache). We could call it for example `buildRunner` and `Runner` would be a new struct wrapper around `interpreter` and would just have `evaluate{,Snippet}{,Stream,Multi}` methods.

**Comment by sbarzowski** [comment]
It's done. It's not super elegant - the API is the same, but the cache is preserved and flushed only when extVars change (which in general invalidate evaluations of all files).

**Comment by Quentin-M** [comment]
Wow, thanks a lot @sbarzowski. This is amazing, we still meant to give another go to a PR but it fell down the list a little bit.
