### ISSUE TITLE
proper way to parse & walk the AST?

### ISSUE THREAD

**Issue by jamesonjlee** [google/go-jsonnet#226]
Hello,

I am trying to walk the AST tree for some jsonnet files to extract imports (finding dependencies).

when I use `vm.go`'s `SnippetToAST` and walk using Node.Children() I eventually panic with `panic: directChildren: Unknown node &ast.DesugaredObject{NodeBase:ast.NodeBase{loc:ast.LocationRange{FileName:"... ` when I encounter helper jsonnets that is an object with functions

when I implement the function without desugaring / analyze, it panics with ObjectComp & Paren error (which I was able to bypass and complete the AST walk with the following patch https://github.com/jamesonjlee/go-jsonnet/commit/13c4ad47d5278225ff57064dcd34d0ef4de2d4dd)

is there a right way to walk the AST tree? do i need to implement my own version of the `static_analyzer.go`?

**Comment by sbarzowski** [comment]
Using `Children` is the right way. So you have actually found two bugs.  `Children` should work with both with ASTs before and after desugaring.

Could you send us the PR with your patch?

I'll fix the issue with DesugaredObject and add tests to ensure that it doesn't crash for any AST in our test suite.

Thank you for helping us polish the less exercised parts of our code.
