### ISSUE TITLE
cannot find package

### ISSUE THREAD

**Issue by nanodeath** [google/go-jsonnet#235]
I'm attempting to follow the build instructions, but when I run `go build` I get 

```
$ go build
cmd.go:32:2: cannot find package "github.com/fatih/color" in any of:
        C:\Go\src\github.com\fatih\color (from $GOROOT)
        C:\Users\Maxwell\go-workspace\src\github.com\fatih\color (from $GOPATH)
```

```
$ go version
go version go1.10.3 windows/amd64
```

Any suggestions?

**Comment by sbarzowski** [comment]
Quick fix is `go get "github.com/fatih/color"`. 

I don't know why `go get github.com/google/go-jsonnet` didn't install this dependency.

**Comment by nanodeath** [comment]
Thanks @sbarzowski.

After I run

```
$ go get "github.com/fatih/color"
$ go get github.com/google/go-jsonnet/ast
```

I can now `go build` without it erroring, but it doesn't print anything nor generate `jsonnet` or `jsonnet.exe`. Weird.

**Comment by sbarzowski** [comment]
Do you run `go build` in `jsonnet/` subdirectory? Only there you have a main package which produces a binary. Running `go build` in project root checks that it compiles, but it doesn't actually have any target executable.

**Comment by nanodeath** [comment]
Ack, no I did not -- I was running it from the root. Total user error. Looks like everything's working now. Thanks @sbarzowski!

(maybe there could be a default target that prints out a helpful warning, of some kind?)
