### ISSUE TITLE
Use vendoring

### ISSUE THREAD

**Issue by tamalsaha** [google/go-jsonnet#237]
Have you considering adding vendoring? Otherwise provide pre-built binaries so we can just download and put in the bin folder?

**Comment by seh** [comment]
For the record, I found that running _dep init_ in the root directory took care of vendoring the dependencies, per the following output:
```
  Locking in v0.0.9 (167de6b) for transitive dep github.com/mattn/go-colorable
  Using ^1.0.0 as constraint for direct dep github.com/sergi/go-diff
  Locking in v1.0.0 (1744e29) for direct dep github.com/sergi/go-diff
  Using ^1.7.0 as constraint for direct dep github.com/fatih/color
  Locking in v1.7.0 (5b77d2a) for direct dep github.com/fatih/color
  Locking in v0.0.4 (6ca4dbf) for transitive dep github.com/mattn/go-isatty
  Locking in master (66b7b13) for transitive dep golang.org/x/sys
```
Those were its default choices, which we could refine as necessary.

**Comment by michaeljs1990** [comment]
I think this ticket can be closed out now with master using go modules unless we want to do more work around providing pre built binaries.
