### ISSUE TITLE
Extend extVar with a default value

### ISSUE THREAD

**Issue by dlespiau** [google/go-jsonnet#247]
It'd be quite useful to be able to provide default value to a `std.extVar` when it's not provided. Right now not specifying an `extVar` throws an error if not defined with no way to catch that condition. We probably also want to make a distinction between no `extVar` specified and a specified empty `extVar` (`''`). And of course, be backward-compatible is a plus.

Considering the above, I was thinking we could add a second, optional, parameter:
```
extVar(name, defaultValue=null)
```
1. if `name` doesn't exist and `defaultValue` is not provided, throw an error like today
2. if `name` doesn't exist and `defaultValue` is provided, return `defaultValue`

**Comment by sbarzowski** [comment]
This was a deliberate decision, please see:
- https://github.com/google/jsonnet/issues/316#issuecomment-306069666
- https://github.com/google/jsonnet/issues/316#issuecomment-398604467
- https://github.com/google/jsonnet/pull/550

Basically the current recommendation is to always explicitly state all extVars, so that they are discoverable. 

Note that TLA (top level argument) mechanism allows default values and doesn't have discoverability problem. I would recommend it over extVars most of the time anyway.

**Comment by dlespiau** [comment]
Alright, thanks for digging up the reasoning behind it, closing then :)

**Comment by steeling** [comment]
discoverability aside, I'd like an option to not have to rewrite my entire set of configs as a set of functions, and plumb the value through.

What about setting std.extVar("<name>", <default_value>), although that does not satisfy the discoverability isssue, it solves $550

**Comment by sbarzowski** [comment]
> What about setting std.extVar("", <default_value>), although that does not satisfy the discoverability isssue, it solves $550

It has another issue – you can have different default values in different places, so it's potentially impossible to pass any extVar value which will have the same output as not passing it at all. It is pretty much equivalent to passing a "supernull" value that the user cannot normally create. 

> I'd like an option to not have to rewrite my entire set of configs as a set of functions, and plumb the value through.

Well, you have other options:
1) Why not just pass all the extvars that you need? If you have a lot of them you can pass an object which contains them all (you can have that object in a file).
2) When you pass an object as extVar you can actually have optional fields. Your code can check if a field exist in an object. (This is not something I would generally recommend, but you can emulate your feature this way).
3) With TLAs you don't need to wrap every little bit i a function. You can wrap whole files and only pass them in imports (this is something you couldn't/wouldn't do in most languages, but it's perfectly valid in Jsonnet).
4) If these values don't really change maybe you can actually put what you planned as extrVars in an importable file?

I'll be happy to help you find the best solution for your use case if you share more.

**Comment by steeling** [comment]
Thanks for the advice!

So our situation is like the following:

```
local main = import '...';

function(namespace='default') {
   main: main {
      namespace:: namespace,
   },
}
```

I actually just got this to work as I was typing this with:

```
function(namespace='default') {} + main {
      namespace:: namespace,
   },
```

Is there a better way to do this?

**Comment by sbarzowski** [comment]
I'm not sure I understand, but I can say a few things:
* You don't need `{}` after function(args). `{} + obj` is equivalent to `obj`. So the following should work just fine:
```
function(namespace='default') main {
      namespace:: namespace,
   },
```
* You can have imports inside the function, e.g.:
```
function(namespace='default')

local main = (import '...')(namespace); # You can call the function in the imported file to pass the arguments
main {
  foo: "bar"
}
```
The pattern with overriding a field ofc also works.
