### ISSUE TITLE
Difference in go-jsonnet and jsonnet substr function

### ISSUE THREAD

**Issue by michaeljs1990** [google/go-jsonnet#272]
When using substr in the go-jsonnet version and asking for a substring larger than the string given to it go-jsonnet fails. For now I have just guarded my calls to substr with a wrapper that first checks length and then calls substr if needed.

```
$ go get -u github.com/google/go-jsonnet/cmd/jsonnet
$ ~/gocode/bin/jsonnet -version
Jsonnet commandline interpreter v0.12.1
```

```
$ jsonnet test.jsonnet 
{
   "break": "me down"
}

$ ~/gocode/bin/jsonnet test.jsonnet 
RUNTIME ERROR: Index 7 out of bounds, not within [0, 7)
	<std>:48:51-64	function <anonymous>
		
	<std>:48:7-66	builtin function <join>
	test.jsonnet:2:10-38	object <anonymous>
	During manifestation	

$ cat test.jsonnet             
{
  break: std.substr("me down", 0, 10),
}
```

This was my quick hack around it if anyone else comes across this.
```
  substr(str, start, end)::
    if std.length(str) > end then
      std.substr(str, start, end)
    else
      std.substr(str, start, std.length(str)),
```

**Comment by sbarzowski** [comment]
Good catch, thank you for reporting

**Comment by seh** [comment]
Note that the hacked `substr` doesn't handle a positive argument value for the "start" parameter.

**Comment by michaeljs1990** [comment]
> Note that the hacked `substr` doesn't handle a positive argument value for the "start" parameter.

Fixed up so that works as intended.
