### ISSUE TITLE
v0.12.1 tag seems to be on the wrong commit

### ISSUE THREAD

**Issue by nshalman** [google/go-jsonnet#277]
I'm working on packaging go-jsonnet for Nix and NixOS over in NixOS/nixpkgs#60529 and was [asked](https://github.com/NixOS/nixpkgs/pull/60529#discussion_r283085198) to reference a tag rather than a commit.

I noticed that the [google/go-jsonnet@v0.12.1](https://github.com/google/go-jsonnet/releases/tag/v0.12.1) and [google/go-jsonnet@v0.12.0](https://github.com/google/go-jsonnet/releases/tag/v0.12.0) tags are currently both pointed at the same commit (namely google/go-jsonnet@493c45a403d25435774370ddfa6363906a65c23c.)

It would be nice for the v0.12.1 tag to be correctly updated or for a new release to be made with a properly updated tag.

Thanks so much for your work!

**Comment by sparkprime** [comment]
It's because on the Go version the releases were the same. I suppose I should have made a release just to bump the version reported by `--version` instead of making an alias, but I didn't do that :)

There should be a new release coming very soon though.

**Comment by sparkprime** [comment]
The new release has a tag in both repos.
