### ISSUE TITLE
Missing stack trace when merging objects containing null as value 

### ISSUE THREAD

**Issue by davidreuss** [google/go-jsonnet#282]
Hey,

I spent way too long on this specific issue until i realized it was coming from externally parsed YAML which contained a key with an "empty" value, resulting in a null.

It would be great if the `go` version of `jsonnet` dealt with this the same way that the c++ version does, where i get a proper stacktrace.

```
$ cat a.jsonnet
local a(input) = input + {
  a+: {},
};

a({a: null})
```

```
$ jsonnet a.jsonnet
RUNTIME ERROR: Unexpected type null
	During manifestation
```

The cpp version of `jsonnet` handles this much more gracefully:

```
$ /usr/local/bin/jsonnet a.jsonnet
RUNTIME ERROR: binary operator + requires matching types, got null and object.
	a.jsonnet:(1:26)-(3:2)	object <anonymous>
	During manifestation
```

Let me know if you need anything else.

Thanks in advance.

**Comment by sbarzowski** [comment]
Thanks for letting us know about this.

It definitely shouldn't happen that there is a runtime error without any location information. The error message shouldn't be that hard to improve, too.

**Comment by ghostsquad** [comment]
@sbarzowski is it possible to extend the stack trace in this case to also point out where the original value of `a` was evaluated from?

**Comment by sbarzowski** [comment]
> to also point out where the original value of a was evaluated from?

Hmmm... but how would that look like? Let's say you have something like `a + b`, which results in an error. Are you going to show the origin of a, or b or of both? Also what would this origin mean in case `a` is a function call, or array indexing?

**Comment by davidreuss** [comment]
👋  ... this is still an issue as of jsonnet release 0.16.0 :(

**Comment by abirdZendesk** [comment]
I just experienced the same issue yesterday and spent a huge amount of time debugging it and looking in the wrong place because that's where the `unexpected type null` claimed to originate from. Would it be possible to improve the Runtime Error to be inline with what we get from using c++ jsonnet as mentioned in the issue?

**Comment by davidreuss** [comment]
ugh, was hoping that this might've been fixed with v0.17.0 -- but doesn't look like it.. 

any hope for resolve here? 🙏

**Comment by sbarzowski** [comment]
Argh. Sorry I missed it and thanks for checking it.

I think I know what's going on now. I'll update this issue once I know more.

**Comment by sbarzowski** [comment]
Ok, so what is going on is that `+:` does not produce a separate stack trace entry. We can add it.

We can also think about adding stack trace entries for going deeper into the manifested object. This kind of entries would be completely artificial and would not necessarily correspond to any code location, but could still be helpful in figuring out what's going on. With these changes we should be able to produce something like this:
```
RUNTIME ERROR: binary operator + requires matching types, got null and object.
	a.jsonnet:(2:3)-(2:9)	object <anonymous>
        Field "a"
	During manifestation
```

**Comment by sbarzowski** [comment]
Related: we don't show which object assertion failed, e.g. in `{ assert false }`.
