### ISSUE TITLE
how to build jsonnetfmt binary go-jsonnet

### ISSUE THREAD

**Issue by nonetheless** [google/go-jsonnet#298]
how can i build a jsonnetfmt binary in v0.13.0 go-jsonnet

**Comment by sbarzowski** [comment]
There is no separate implementation provided for `jsonnetfmt` in go-jsonnet. Please use the one from https://github.com/google/jsonnet. 

Rationale:
The jsonnet language has a quite precise spec, so it's not that hard maintaining compatibility between the go-jsonnet and cpp-jsonnet for the interpreter. Formatting however is implementation-defined and it's important that everyone uses the same one, so we didn't duplicate it here.
