### ISSUE TITLE
call renderJsonnet error:INTERNAL ERROR: (CRASH) interface conversion: jsonnet.value is *jsonnet.valueNull, not *jsonnet.valueObject

### ISSUE THREAD

**Issue by yiye93** [google/go-jsonnet#302]
I want to use jsonnet a new feature cache, so i pull master branch, but  error is like this:
Error evaluating jsonnet snippet: %!(EXTRA *errors.errorString=INTERNAL ERROR: (CRASH) interface conversion: jsonnet.value is *jsonnet.valueNull, not *jsonnet.valueObject

**Comment by sbarzowski** [comment]
Hi, 

I'll be happy to help. Could you provide more details? Does it happen when you evaluate some specific Jsonnet code or on every program? Are you running Jsonnet as a CLI command or as a library?

I guess the stack trace you posted in the other issue belongs here:
```
INTERNAL ERROR: (CRASH) interface conversion: jsonnet.value is *jsonnet.valueNull, not *jsonnet.valueObject
goroutine 1 [running]:
runtime/debug.Stack(0xc000305538, 0x12bf0e0, 0xc0000859b0)
/Users/lucky/Documents/software/go_1_11/go/src/runtime/debug/stack.go:24 +0xa7
github.com/google/go-jsonnet.(*VM).evaluateSnippet.func1(0xc000305af0)
/Users/lucky/Documents/project/go/sivs/src/github.com/google/go-jsonnet/vm.go:137 +0x6e
panic(0x12bf0e0, 0xc0000859b0)
/Users/lucky/Documents/software/go_1_11/go/src/runtime/panic.go:513 +0x1b9
github.com/google/go-jsonnet.buildStdObject(0xc0000a0140, 0xc00009c780, 0x2d62272c2e9222c8, 0xc0003058e0)
/Users/lucky/Documents/project/go/sivs/src/github.com/google/go-jsonnet/interpreter.go:1102 +0x405
github.com/google/go-jsonnet.buildInterpreter(0xc000085740, 0xc0000857a0, 0x1f4, 0x1372b40, 0xc00009c6c0, 0x3, 0xc0003059f0, 0x1270ebf)INTERNAL ERROR: (CRASH) interface conversion: jsonnet.value is *jsonnet.valueNull, not *jsonnet.valueObject
goroutine 1 [running]:
runtime/debug.Stack(0xc000305538, 0x12bf0e0, 0xc0000859b0)
/Users/lucky/Documents/software/go_1_11/go/src/runtime/debug/stack.go:24 +0xa7
github.com/google/go-jsonnet.(*VM).evaluateSnippet.func1(0xc000305af0)
/Users/lucky/Documents/project/go/sivs/src/github.com/google/go-jsonnet/vm.go:137 +0x6e
panic(0x12bf0e0, 0xc0000859b0)
/Users/lucky/Documents/software/go_1_11/go/src/runtime/panic.go:513 +0x1b9
github.com/google/go-jsonnet.buildStdObject(0xc0000a0140, 0xc00009c780, 0x2d62272c2e9222c8, 0xc0003058e0)
/Users/lucky/Documents/project/go/sivs/src/github.com/google/go-jsonnet/interpreter.go:1102 +0x405
github.com/google/go-jsonnet.buildInterpreter(0xc000085740, 0xc0000857a0, 0x1f4, 0x1372b40, 0xc00009c6c0, 0x3, 0xc0003059f0, 0x1270ebf)
```

**Comment by yiye93** [comment]
I am very glad that you can reply to me in time. I running Jsonnet as a library and the stack trace i posted in the other issue as you guessed

**Comment by yiye93** [comment]
the panic happen on every jsonnet code and  the main calling code is as follows:

// Takes a list of jsonnet files and imports each one and mixes them with "+"
func renderJsonnet(files []string, param string, exParam map[string]string, prune bool) (tmpl string, err error) {

	// empty slice
	jsonnetPaths := files[:0]

	// range through the files
	for _, s := range files {
		jsonnetPaths = append(jsonnetPaths, fmt.Sprintf("(import '%s')", s))
	}

	// Create a JSonnet VM
	vm := jsonnet.MakeVM()

	for k, v := range exParam {
		vm.ExtVar(k, v)
	}

	// Join the slices into a jsonnet compat string
	jsonnetImport := strings.Join(jsonnetPaths, "+")

	if param != "" {
		jsonnetImport = "(" + jsonnetImport + ")" + param
	}
	if prune {
		// wrap in std.prune, to remove nulls, empty arrays and hashes
		jsonnetImport = "std.prune(" + jsonnetImport + ")"
	}

	// render the jsonnet
	//out, err := vm.EvaluateSnippet("file", jsonnetImport)
	out, err := vm.EvaluateSnippet("file", jsonnetImport)
	if err != nil {
		seelog.Errorf("Error evaluating jsonnet snippet: ", err)
		return
	}
	return tmpl, err
}

**Comment by sbarzowski** [comment]
@yiye93 I think I know what's going on. We have autogenerated code for stdlib AST (it's much faster than parsing it every time). Recently we changed how we store it and apparently in your case it's not loaded properly.

Can you try adding the following import as a workaround?
```
import (
	// Make sure real stdlib is loaded (workaround https://github.com/google/go-jsonnet/issues/302)
	_ "github.com/google/go-jsonnet/astgen"
)
```

Please let me know if this works. If it does, it will confirm my hypothesis and I will prepare a proper fix so that the workaround is no longer needed.

**Comment by yiye93** [comment]
@sbarzowski  Yes, the problem is solved and the new feature is so fast . I am very grateful to you for solving  the problem. thank you!

**Comment by seh** [comment]
@sbarzowski, I am surprised that that import-for-side-effect above still works; I added it in 440c4b1083e36375153db09aea59d8c4b8296c56, but had then _intended_ to remove it in 6b74d9e8eb0ad19ca9c5b7ac8418852340ec412b, both as part of #281, having waffled on which was the right way to include the standard library in programs that needed it.

Right now—unintentionally—there's a "belt-and-suspenders" installation going on: the assignment to `ast.StdAst` happens twice, both in _dupmstdlibast.go_'s `main.init`, and again in various commands and test programs. I'd prefer that there be only one way.

My earlier intention is documented in [here](https://github.com/google/go-jsonnet/pull/281#issue-282322472):
> - Install the standard library AST into the `ast` package explicitly  
>   The AST generated in the `astgen` package is made available to programs that import it, but it doesn't automatically set this AST as the one used by the `ast` package. Doing so is possible in an `init` function in the generated in the `astgen` package, but setting it up automatically there felt too mysterious. Instead, do it explicitly where necessary: in the _jsonnet_ tool and in the test package that uses it.

I'm fine with reversing that decision again. One way or the other, I think we should settle on just one way to get this installation done.

**Comment by sbarzowski** [comment]
@seh Thanks for providing more context. 

> One way or the other, I think we should settle on just one way to get this installation done.

I couldn't agree more. And if it requires some extra steps for the users of the library, it should at least result in a clear error message if they forget about it.

I was wondering, if I was able to make `dumpstdlibast` independent from jsonnet package, could we just use `astgen` directly in jsonnet package (and get rid completely of the ast.Stdlib and its "installation")? We would no longer have issues with circular dependencies. I would need to extract `jsonnet.SnippetToAST` to a separate package, but that should be very doable.

**Comment by seh** [comment]
If _dumpstdlibast_ didn't depend on the "jsonnet" package (and maybe the "parser" package either), and you could cut the dependency on the "ast" package, then a whole bunch of difficulty would go away. Probably half of the time that I spent wranging with #281 was due to that circular dependency.

I had ranted and asked questions about it in [this thread in the "jsonnet" channel in the "Kubernetes" Slack team](https://kubernetes.slack.com/archives/C6JLE4L9X/p1558226568057700). For a few days I had a dependency graph angrily scribbled on a napkin that I was carrying around with me as I was trying to understand the problem and plan a solution. I threw it away when I thought this was settled; that was a mistake.

If _dumpstdlibast_ could use the "ast" package without bumping into any references to the very objects it generates, then we'd be in good shape.

**Comment by sbarzowski** [comment]
I think it was fixed a while back (around https://github.com/google/go-jsonnet/pull/310).
