### ISSUE TITLE
MemoryImporter does not support relative imports

### ISSUE THREAD

**Issue by ozkar99** [google/go-jsonnet#307]
`MemoryImporter.Import` does not check if path imports are absolute (nor does it sanitize them if not the case).

Is this a conscious  decision? or am i looking at a bug here?

**Comment by sbarzowski** [comment]
It's not a bug. `MemoryImporter` is supposed to be the simplest importer possible. It doesn't really consider any hierarchical paths - it's just a key-value store. Imported "paths" are treated as opaque strings. And it's formally a perfectly valid importer.

Of course there is nothing stopping you from creating a `FancyMemoryImporter` which handles hierarchical paths. Doing so should be fairly simple and doesn't require using any other Jsonnet concepts. The comment here should explain everything you need to know about this interface https://github.com/google/go-jsonnet/blob/master/imports.go#L28.

Please, let me know if you have any further questions.

**Comment by ozkar99** [comment]
Thanks for the quick response, @sbarzowski thats what i ended up doing, i just wanted to know if i needed to create a PR for the "fix", but since its by design theres no need for it.
