### ISSUE TITLE
Support native callbacks in c-bindings

### ISSUE THREAD

**Issue by sparkprime** [google/go-jsonnet#323]
Requirement to move Kapitan from C++ to Go

**Comment by alldroll** [comment]
Could you please describe more what should be done on this issue? I would like to take it, but I am not familiar with this naming :(

**Comment by sparkprime** [comment]
Sure:

The Jsonnet C API has a function here for registering native functionality:
https://github.com/google/jsonnet/blob/master/include/libjsonnet.h#L186

The c-bindings around go-jsonnet don't implement it yet:
https://github.com/google/go-jsonnet/blob/master/c-bindings/libjsonnet.cpp#L63

Similarly for the import callbacks (slightly different API, but same concept).

What I guess this needs to do is make a function on the Go side that encapsulates the provided C function, and register that function with the underlying Go implementation's corresponding API:
https://github.com/google/go-jsonnet/blob/master/vm.go#L159

**Comment by sbarzowski** [comment]
The biggest pain here comes from handling the arguments, with all the restrictions that CGo has. Native functions take arguments which are plain JSON and return plain JSON. These JSON values are constructed using jsonnet_json_* family of functions.

If you have any problems/questions I'll be happy to help!
