### ISSUE TITLE
Python API

### ISSUE THREAD

**Issue by alldroll** [google/go-jsonnet#333]
We have implemented c bindings for `_native`, `_import` callbacks.

In order to integrate `go-jsonnet` for [kapitan](https://github.com/deepmind/kapitan), we should build python API using shared library generated by `cgo` (as it implemented [here](https://github.com/google/jsonnet/blob/master/python/_jsonnet.c))

What do you think about it? Here is a slight [discussion](https://github.com/deepmind/kapitan/issues/144#issuecomment-544441385)

**Comment by sbarzowski** [comment]
It should be possible to copy the Python setup from google/jsonnet, modify it a little bit and create a new Python package which will be backed by go-jsonnet. Once it is stable and early users are happy, we may want to replace the old `jsonnet` package with it.

The relevant files seem to be:
* https://github.com/google/jsonnet/blob/master/setup.py
* https://github.com/google/jsonnet/tree/master/python

The library is a drop-in replacement so I think the modifications will be limited mostly to changing `setup.py`.

**Comment by alldroll** [comment]
Thanks, let me try to do it
