### ISSUE TITLE
RuntimeError: RUNTIME ERROR: Not enough values to format: 1, expected at least 1

### ISSUE THREAD

**Issue by gagandeep** [google/go-jsonnet#334]
I am getting the following error
```RuntimeError: RUNTIME ERROR: Not enough values to format: 1, expected at least 1```

That code is running for others but failing for just one. I am not able to pin-point the exact case where it's failing.

Using Python jsonnet version 0.14
Downgrading jsonnet version to <0.14 don't solved the Runtime Error.

**Comment by sbarzowski** [comment]
Closing in favor of https://github.com/google/jsonnet/issues/726. Currently distributed Python package uses C++ implementation (i.e. google/jsonnet) under the hood. Conveniently that repo also is the source of truth for the stdlib (which is the most relevant part for this issue).
