### ISSUE TITLE
[feature request] load arbitrary data from file

### ISSUE THREAD

**Issue by hangxie** [google/go-jsonnet#337]
Prefer to be a new function in std lib, which can load arbitrary data into a variable from a file, like this:

```
user_data: std.loadData('/path/to/cloud-init.sh');
```

This will keep the non-json files separated from jsonnet to make maintenance easier (format and readibility, etc.)

**Comment by sbarzowski** [comment]
Have you tried using `importstr`? For example: `importstr '/path/to/cloud-init.sh'`.

**Comment by hangxie** [comment]
> Have you tried using `importstr`?

Makes sense.
