### ISSUE TITLE
Error while importing files from multiple jsonnet files using same path

### ISSUE THREAD

**Issue by buremba** [google/go-jsonnet#349]
I'm trying to import a libjsonnet file in my Jsonnet file but it throws the following exception:

```
Error installing recipe: error while evaluating recipe, INTERNAL ERROR: (CRASH) importer problem: a different instance of Contents returned when importing "./common.libsonnet" again goroutine 4626 [running]: runtime/debug.Stack(0xc0067fd0a8, 0x9e67c0, 0xc00549e4f0) /usr/local/go/src/runtime/debug/stack.go:24 +0x9d github.com/google/go-jsonnet.(*VM).evaluateSnippet.func1(0xc0067ff5f0) /go/pkg/mod/github.com/google/go-jsonnet@v0.13.0/vm.go:129 +0x57 panic(0x9e67c0, 0xc00549e4f0) /usr/local/go/src/runtime/panic.go:679 +0x1b2 github.com/google/go-jsonnet.(*ImportCache).importData(0xc00031c140, 0xc000ce6260, 0x14, 0xc004b58860, 0x12, 0x37, 0x8, 0x8, 0xc0067fd260, 0x15) /go/pkg/mod/github.com/google/go-jsonnet@v0.13.0/imports.go:92 +0x282 github.com/google/go-jsonnet.(*ImportCache).ImportCode(0xc00031c140, 0xc000ce6260, 0x14, 0xc004b58860, 0x12, 0xc000176050, 0xc0058b6f00, 0xc00520dc50, 0xc000f72320, 0x0, ...) /go/pkg/mod/github.com/google/go-jsonnet@v0.13.0/imports.go:129 +0x74 github.com/google/go-jsonnet.(*interpreter).evaluate(0xc000176050, 0xbdc860, 0xc0058b6f00, 0x1, 0x0, 0x75bcd15, 0xc003a7bf50, 0xc003a96100) /go/pkg/mod/github.com/google/go-jsonnet@v0.13.0/interpreter.go:465 +0x33fc github.com/google/go-jsonnet.(*interpreter).EvalInCleanEnv(0xc000176050, 0xc004e23030, 0x0, 0xc0037cdc80, 0xbdc860, 0xc0058b6f00, 0x7f6698082800, 0x0, 0x203000, 0x0, ...) /go/pkg/mod/github.com/google/go-jsonnet@v0.13.0/interpreter.go:916 +0xc7 github.com/google/go-jsonnet.(*cachedThunk).getValue(0xc004188f80, 0xc000176050, 0xc004e23030, 0x0, 0x1, 0x8, 0xd0, 0xd0) /go/pkg/mod/github.com/google/go-jsonnet@v0.13.0/thunks.go:76 +0x8c github.com/google/go-jsonnet.(*interpreter).evaluate(0xc000176050, 0xbdcc60, 0xc004e23030, 0x0, 0x30, 0x8, 0xd0, 0xd0) /go/pkg/mod/github.com/google/go-jsonnet@v0.13.0/interpreter.go:508 +0x11c7 github.com/google/go-jsonnet.(*interpreter).evaluate(0xc000176050, 0xbdc920, 0xc000457480, 0x0, 0xc004188e01, 0xc0067fe720, 0x40da06, 0xc004188ec0) /go/pkg/mod/github.com/google/go-jsonnet@v0.13.0/interpreter.go:429 +0x693 github.com/google/go-jsonnet.(*interpreter).evaluate(0xc000176050, 0xbdc6e0, 0xc00013b700, 0x1, 0xc001151630, 0x0, 0xc003a96180, 0xbdcb00) /go/pkg/mod/github.com/google/go-jsonnet@v0.13.0/interpreter.go:330 +0x28c9 github.com/google/go-jsonnet.(*interpreter).EvalInCleanEnv(0xc000176050, 0xc000b4f300, 0x0, 0xc0067fed50, 0xbdc6e0, 0xc00013b700, 0xc003a96000, 0xc00418a4e0, 0xc00418a4e0, 0x0, ...) /go/pkg/mod/github.com/google/go-jsonnet@v0.13.0/interpreter.go:916 +0xc7 github.com/google/go-jsonnet.(*codeUnboundField).evaluate(0xc00549e470, 0xc000176050, 0xc000b4f300, 0x0, 0xbdf0c0, 0xc001151630, 0x0, 0xc003a96180, 0xc0050a3e10, 0xa, ...) /go/pkg/mod/github.com/google/go-jsonnet@v0.13.0/thunks.go:100 +0xa8 github.com/google/go-jsonnet.objectIndex(0xc000176050, 0xc000b4f300, 0x0, 0xbdf0c0, 0xc001151630, 0x0, 0xc0050a3e10, 0xa, 0xc0067fef10, 0x40eeed, ...) /go/pkg/mod/github.com/google/go-jsonnet@v0.13.0/value.go:653 +0x223 github.com/google/go-jsonnet.(*valueSimpleObject).index(0xc001151630, 0xc000176050, 0xc000b4f300, 0x0, 0xc0050a3e10, 0xa, 0x0, 0x0, 0x0, 0x0) /go/pkg/mod/github.com/google/go-jsonnet@v0.13.0/value.go:520 +0x82 github.com/google/go-jsonnet.(*interpreter).manifestJSON(0xc000176050, 0xc000b4f300, 0x0, 0xbd1c00, 0xc001151630, 0xc001151630, 0x0, 0x0, 0x0) /go/pkg/mod/github.com/google/go-jsonnet@v0.13.0/interpreter.go:671 +0x550 github.com/google/go-jsonnet.(*interpreter).manifestJSON(0xc000176050, 0xc000b4f300, 0x0, 0xbd1a80, 0xc000e3eae0, 0x6, 0xbd1a80, 0xc000e3eae0, 0x0) /go/pkg/mod/github.com/google/go-jsonnet@v0.13.0/interpreter.go:651 +0x9cf github.com/google/go-jsonnet.(*interpreter).manifestJSON(0xc000176050, 0xc000b4f300, 0x0, 0xbd1c00, 0xc000176280, 0xc0009e2e10, 0x0, 0x0, 0xc00031c140) /go/pkg/mod/github.com/google/go-jsonnet@v0.13.0/interpreter.go:676 +0x5a2 github.com/google/go-jsonnet.(*interpreter).manifestAndSerializeJSON(0xc000176050, 0xc0067ff4b8, 0xc000b4f300, 0x0, 0xbd1c00, 0xc000176280, 0xc000b4f301, 0x0, 0x0, 0x0, ...) /go/pkg/mod/github.com/google/go-jsonnet@v0.13.0/interpreter.go:793 +0x5a github.com/google/go-jsonnet.evaluate(0xbdc760, 0xc0000b2c80, 0xc0009e2db0, 0xc0009e2de0, 0xc0009e2e10, 0x1f4, 0xbcd260, 0xc0000ae028, 0xc000ff5500, 0x7f6698758ad0, ...) /go/pkg/mod/github.com/google/go-jsonnet@v0.13.0/interpreter.go:1228 +0x255 github.com/google/go-jsonnet.(*VM).evaluateSnippet(0xc000284410, 0xadef47, 0x4, 0xc0009e4340, 0x194, 0x0, 0x0, 0x0, 0x0, 0x0) /go/pkg/mod/github.com/google/go-jsonnet@v0.13.0/vm.go:138 +0x308 github.com/google/go-jsonnet.(*VM).EvaluateSnippet(0xc000284410, 0xadef47, 0x4, 0xc0009e4340, 0x194, 0x194, 0x0, 0x4, 0xadf869) /go/pkg/mod/github.com/google/go-jsonnet@v0.13.0/vm.go:160 +0x69 main.(*RecipeGit).RenderRecipe(0xc000262420, 0xc000b1a420, 0xc00034a0e0, 0x9, 0xadf82d) /app/main.go:181 +0x809 main.handleRenderRequest(0xbd9720, 0xc00031a1c0, 0xc000016100) /app/main.go:309 +0x231 net/http.HandlerFunc.ServeHTTP(0xb13e88, 0xbd9720, 0xc00031a1c0, 0xc000016100) /usr/local/go/src/net/http/server.go:2007 +0x44 net/http.(*ServeMux).ServeHTTP(0xc0000c9b40, 0xbd9720, 0xc00031a1c0, 0xc000016100) /usr/local/go/src/net/http/server.go:2387 +0x1bd gopkg.in/DataDog/dd-trace-go.v1/contrib/internal/httputil.TraceAndServe(0xbcd3e0, 0xc0000c9b40, 0xbd9720, 0xc00031a1c0, 0xc000016000, 0xae4f22, 0x11, 0xc0002941c0, 0x13, 0xc0000ae028, ...) /go/pkg/mod/gopkg.in/!data!dog/dd-trace-go.v1@v1.17.0/contrib/internal/httputil/trace.go:37 +0x513 gopkg.in/DataDog/dd-trace-go.v1/contrib/net/http.(*ServeMux).ServeHTTP(0xc000110a60, 0xbd8da0, 0xc000300380, 0xc000016000) /go/pkg/mod/gopkg.in/!data!dog/dd-trace-go.v1@v1.17.0/contrib/net/http/http.go:50 +0x13b net/http.serverHandler.ServeHTTP(0xc00010e1c0, 0xbd8da0, 0xc000300380, 0xc000016000) /usr/local/go/src/net/http/server.go:2802 +0xa4 net/http.(*conn).serve(0xc0003a6140, 0xbda6e0, 0xc00031a000) /usr/local/go/src/net/http/server.go:1890 +0x875 created by net/http.(*Server).Serve /usr/local/go/src/net/http/server.go:2927 +0x38e Please report a bug here: https://github.com/google/go-jsonnet/issues
```

If I try to import the same file using the same path from multiple jsonnet files, I get the exception above.

The file sthat I'm trying to compile are these files and the following PR fixes the issue for now:
https://github.com/rakam-io/recipes/commit/18fccc322acf4cd6f8b18c584f64a34ffc3d3dc4#diff-19f5498ce9f2bb6aec9b9c7e67abf482

**Comment by sh0rez** [comment]
Are you using the jsonnet cli tool, or the library in your own go application?

**Comment by sbarzowski** [comment]
Thanks for reporting. I need a few more details to help you:

1) How do you call Jsonnet? Based on the stack trace it seems like there is some Go program which uses Jsonnet as a library. Is the source available? Can you point me to the piece of code where Jsonnet is used.
2) Is there a custom importer in use? This error was meant to catch the situation when custom importer doesn't do enough caching. More precisely it tries to verify this: https://github.com/google/go-jsonnet/blob/master/imports.go#L47
3) I can see that go-jsonnet 0.13 is used. It is not the most recent release. Can you check if you have the same problem on the current master?

**Comment by buremba** [comment]
Wow, thanks for getting back to me so quickly. 
1. We use the following library in Go: `github.com/google/go-jsonnet v0.13.0`. The library scans the repository, finds the files that end with `.model.jsonnet` and compiles them.
2. We don't use any custom importer, the file that I'm trying to import is already in the repository.
3. We will update the Jsonnet version and try it again.

**Comment by buremba** [comment]
Sorry for the delay, it took some time for us to upgrade to 0.14. It looks like the problem still exists, if I have 2 Jsonnet files importing the same file, I get the same exception.

@sbarzowski you were right, your custom loader didn't have the caching capability as we didn't go through the documentation in a detailed way. 🙄

Looks like the compiler already caches the files and if we add caching to our code, it will be cached twice. Is there any benefit of calling the file loader again and expecting it to return the same instance>

**Comment by buremba** [comment]
I don't really know you want to let users be able to use their custom `Importer`s so this probably an internal integrity check. I'm closing the issue as this is not actually a bug/feature request for Jsonnet.

**Comment by sbarzowski** [comment]
> I don't really know you want to let users be able to use their custom Importers so this probably an internal integrity check. I'm closing the issue as this is not actually a bug/feature request for Jsonnet.

Writing custom importers is a supported feature. It's an "advanced feature", though. Only a small fraction of Jsonnet users need to be concerned with that at all (authors of Jsonnet-based tooling, for whom the regular importer is not sufficient).

**Comment by sbarzowski** [comment]
> Looks like the compiler already caches the files and if we add caching to our code, it will be cached twice. Is there any benefit of calling the file loader again and expecting it to return the same instance>

Yes. Jsonnet does not assume any specific relationship between (importedFrom, importedPath) and `foundAt`. So it doesn't know if the import wouldn't return an already imported file. Either way it needs to ask the importer for that. I considered splitting this into two calls (one for getting the foundAt, the other for actually fetching the file), but that results in less elegant, more error-prone and potentially less-efficient code (especially in some less common cases, like importers fetching over http).

**Comment by buremba** [comment]
I see the point, thanks for the clarification @sbarzowski! It may be a good idea to separate the implementation errors and use something like `IMPLEMENTATION ERROR` instead of `INTERNAL ERROR` in the error message so that the newbies like us don't get confused. :)

**Comment by sbarzowski** [comment]
Yeah, definitely "internal error" is not the right message here.
