### ISSUE TITLE
Cannot install gojsonnet from PyPI (experimental Python support)

### ISSUE THREAD

**Issue by sbarzowski** [google/go-jsonnet#371]
```
❯ sudo pip install gojsonnet
Collecting gojsonnet
  Downloading https://files.pythonhosted.org/packages/b3/f9/58c1657578f3a8d47b73effdc856a7ce6841711298f22dee61faaf05ff57/gojsonnet-0.15.0.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4herb7e2/gojsonnet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4herb7e2/gojsonnet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-4herb7e2/gojsonnet/pip-egg-info
         cwd: /tmp/pip-install-4herb7e2/gojsonnet/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-4herb7e2/gojsonnet/setup.py", line 63, in <module>
        version=get_version(),
      File "/tmp/pip-install-4herb7e2/gojsonnet/setup.py", line 29, in get_version
        with open(os.path.join(DIR, 'vm.go')) as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-4herb7e2/gojsonnet/vm.go'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by iwoloschin** [comment]
A very quick glance at this makes me think you might just be not including `vm.go` in the python package.  There's a few ways to do that, the easiest is probably to specify `MANIFEST.in` (https://docs.python.org/3/distutils/sourcedist.html#the-manifest-in-template).  Alternatively, you may also be able to use `setuptools-scm` (https://pypi.org/project/setuptools-scm/) to just get version information directly from git.

I can probably take a stab at this if you'd like.

**Comment by sbarzowski** [comment]
> I can probably take a stab at this if you'd like.

That would be great!

Hmmm... I think vm.go is needed only for getting the version. Python bindings use the C interface (compiled libgojsonnet.a) internally.

**Comment by iwoloschin** [comment]
Sure, I'll probably take a look tonight.

**Comment by iwoloschin** [comment]
A very quick fix is in #373, but it continues to naively assume the user has the go toolchain installed.  I'm not sure what can, or should, be done to make that easier, but I imagine that's probably best handled in a separate issue?

**Comment by JoshLipschultz** [comment]
Hi all—what's the current status of the lack-of-toolchain thing? I've recently built a python tool which calls out to Jsonnet, but am seeing render times for moderately-sized files go to 15s, where go-jsonnet gets them in 0.2s. I'd obviously like to use the faster system, but I'm seeing the same thing the author of this issue is wrote about even after installing go (via Homebrew), building `gojsonnet` from source, and trying `pip install gojsonnet` thereafter.

Any other pointers would be appreciated, too!

Thanks!

**Comment by iwoloschin** [comment]
There's a partial solution in #373, it worked locally on my laptop, but apparently there's some more work needed to make a wheel. I'm not sure what needs to happen here, I don't really have any experience with building and publishing python wheels, especially when golang gets added to the mix.

**Comment by JoshLipschultz** [comment]
Cool. Yeah I'm not an expert either, but there are probably two paths to try: either including the `go.vm` and other static dependencies in the wheel, or having `setup.py` build `go-jsonnet` from source using (maybe?) this: https://github.com/asottile/setuptools-golang. There's a link to some examples on that page which look promising.

**Comment by sbarzowski** [comment]
This works now (i.e. you can successfully `pip install gojsonnet`).
