### ISSUE TITLE
Python bindings: "importer problem: a different instance of Contents returned"

### ISSUE THREAD

**Issue by ramaro** [google/go-jsonnet#374]
When trying out the python bindings (commit 31b9ace0f65a5a5717ed9521b57d8d9e18f24070) , I stumbled upon this error:

```
$ py main.py 
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    print(jsonnet_eval("one.jsonnet"))
  File "main.py", line 29, in jsonnet_eval
    return _gojsonnet.evaluate_file(file, import_callback=_search_imports)
RuntimeError: INTERNAL ERROR: (CRASH) importer problem: a different instance of Contents returned when importing "dir/zero.jsonnet" again
goroutine 17 [running, locked to thread]:
runtime/debug.Stack(0xc0002ec910, 0x7f9a35be24a0, 0xc000099330)
```

Here's how to reproduce:

```
$ tree 
.
├── dir
│   └── zero.jsonnet
├── main.py
├── one.jsonnet
└── two.jsonnet
```

```jsonnet
// dir/zero.jsonnet 
{
  zero: 0
}
```

```jsonnet
// one.jsonnet
local two = import "two.jsonnet";
local zero = import "zero.jsonnet";

{
  one: 1,
} + two + zero
```

```jsonnet
// two.jsonnet 
local zero = import "zero.jsonnet";

{
  two: 2
} +  zero
```

Using gojsonnet v0.15.0 (commit 31b9ace0f65a5a5717ed9521b57d8d9e18f24070) works as expected:

``` bash
$ jsonnet one.jsonnet -J . -J dir
{
   "one": 1,
   "two": 2,
   "zero": 0
}
```

However, the following python snippet using import callbacks errors with error reported at the top:

```python
# main.py
import os
import _gojsonnet


def read_import(file_path):
    with open(file_path) as f:
        content = f.read()
        return file_path, content


def search_imports(cwd, import_str, search_paths):
    import_path = os.path.join(cwd, import_str)
    if os.path.exists(import_path):
        try:
            return read_import(import_path)
        except:
            raise
    else:
        for path in search_paths:
            import_path = os.path.join(path, import_str)
            if os.path.exists(import_path):
                return read_import(import_path)
    raise RuntimeError(f"Could not find {import_str}")


def jsonnet_eval(file):
    def _search_imports(cwd, import_str):
        return search_imports(cwd, import_str, [".", "dir", ])
    return _gojsonnet.evaluate_file(file, import_callback=_search_imports)


if __name__ == '__main__':
    print(jsonnet_eval("one.jsonnet"))
```

Am I doing something wrong or is this a real issue?

thanks

**Comment by sbarzowski** [comment]
First of all, thanks for trying out the Python binding for _gojsonnet!

The error message is not optimal, this is not an internal error per se, but a check to ensure that your custom importer satisfies an easy to miss property.

The short answer is that you should cache stuff in search_imports. Preferably both hits and misses for each path that you try. In particular you should return exactly the same object (the same pointer, not just equal) for the same file_path. 

Here are the assumptions about the importer: https://github.com/google/go-jsonnet/blob/master/imports.go#L32
Here is an example compliant implementation in Go: https://github.com/google/go-jsonnet/blob/master/imports.go#L178

BTW does your example work with the C++-backed package (_jsonnet)? If yes, then we should at least document the difference (or hack it, so that it behaves more like _jsonnet).

Related issue: https://github.com/google/go-jsonnet/issues/349

**Comment by ramaro** [comment]
> First of all, thanks for trying out the Python bindings for go-jsonnet!

My pleasure!

>The short answer is that you should cache stuff in search_imports. Preferably both hits and misses for each path that you try. In particular you should return exactly the same object (the same pointer, not just equal) for the same file_path.

I gave this a brief shot when I first noticed the error but without much success. I'll have another look.

>BTW does your example work with the C++-backed package (_jsonnet)? If yes, then we should at least document the difference (or hack it, so that it behaves more like _jsonnet).

Yes it does, if you swap `_gojsonnet` for `_jsonnet` in the example I posted, it works. (The example is based in the code we ship in Kapitan, btw)

thanks

**Comment by ramaro** [comment]
So I've added some crude caching to the `read_import()` function above:

```python
CACHE = {}

def read_import(file_path):
    if file_path not in CACHE:
        with open(file_path) as f:
            content = f.read()
            print("not cached:", file_path, "id:", hex(id(content)), "hash:", hash(content))
            CACHE[file_path] = content
            return file_path, CACHE[file_path]
    else:
        print("cached:", file_path, "id:", hex(id(CACHE[file_path])), "hash:", hash(CACHE[file_path]))
        return file_path, CACHE[file_path]
```
As you can see from the output, the second import of `dir/zero.jsonnet` is cached and returning a reference to the content (same id and hash), however it still errors:

```shell
$ py main.py 
not cached: two.jsonnet id: 0x7f8fbf443ab0 hash: 1293923525331095204
not cached: dir/zero.jsonnet id: 0x7f8fbf1f6370 hash: 2502658012654327476
cached: dir/zero.jsonnet id: 0x7f8fbf1f6370 hash: 2502658012654327476
Traceback (most recent call last):
  File "main.py", line 42, in <module>
    print(jsonnet_eval("one.jsonnet"))
  File "main.py", line 38, in jsonnet_eval
    return jsonnet.evaluate_file(file, import_callback=_search_imports)
RuntimeError: INTERNAL ERROR: (CRASH) importer problem: a different instance of Contents returned when importing "dir/zero.jsonnet" again
goroutine 17 [running, locked to thread]:
runtime/debug.Stack(0xc0002dc910, 0x7f8fbef0c4a0, 0xc000063340)
```

**Comment by sbarzowski** [comment]
This is definitely a bug then. 

Probably either the C-Go adapter or Python-C adapter adds a wrapper object, so from the Go's perspective it's different :-(.

**Comment by sbarzowski** [comment]
Oh, here it is: https://github.com/google/go-jsonnet/blob/master/c-bindings/c-bindings.go#L43.

And it's good that we have this check, because it's also a performance bug.

**Comment by sbarzowski** [comment]
Ok, I have a WIP version where both of your examples work (caching is still recommended, though). A fix should be available soon.

**Comment by sbarzowski** [comment]
Fixed a while back in #384.

**Comment by ramaro** [comment]
Hey @sbarzowski thanks for this and apologies but I just managed to test it and it works!

**Comment by sbarzowski** [comment]
Awesome!
