### ISSUE TITLE
Add tests for 32-bit to Travis

### ISSUE THREAD

**Issue by sbarzowski** [google/go-jsonnet#378]
As far as I can tell, there is no i686 arch in Travis available, but we can just compile stuff in 32-bit mode.

It should let us catch the problems like #376 early.

**Comment by alldroll** [comment]
Do you mean we should add next commands?

```
- GOARCH=arm64 go build
- GOARCH=arm64 go test
- GOARCH=386 go build
- GOARCH=386 go test
- GOARCH=arm go build
...
```

**Comment by sbarzowski** [comment]
Not exactly like that, but it shouldn't be much more complicated. We run a shell script in Travis, so that we also run the tests from cpp-jsonnet.

Perhaps it will be enough to create a Travis configurations exactly like the existing arm64/amd64 ones, but with GOARCH envvar set?

If not then I think the right solution would be to pass an envvar and then hande it in the script here: https://github.com/google/go-jsonnet/blob/v0.15.0/tests.sh#L10 and here https://github.com/google/go-jsonnet/blob/v0.15.0/tests.sh#L20
