### ISSUE TITLE
Modify lexer to catch up with change to C++ jsonnet impl

### ISSUE THREAD

**Issue by sparkprime** [google/go-jsonnet#4]

**Comment by sparkprime** [comment]
@jbeda I'm going to have a go at this now

**Comment by jbeda** [comment]
Sounds good. I was going to play on the plane today but I'll hold off.

**Comment by sparkprime** [comment]
Plenty to do in the parser :)

**Comment by jbeda** [comment]
Is this done now with #5?

**Comment by sparkprime** [comment]
Yep
