### ISSUE TITLE
Are there any plans to make the formatter public?

### ISSUE THREAD

**Issue by harsimranmaan** [google/go-jsonnet#405]
I am interested to add a jsonnet formatter to https://github.com/splunk/qbec. It would help if github.com/google/go-jsonnet/internal/formatter was exposed for public use.

**Comment by sh0rez** [comment]
It's exposed as github.com/google/go-jsonnet/formatter 😜

**Comment by harsimranmaan** [comment]
Thanks. Missed it. Not yet used to new go.dev docs

**Comment by harsimranmaan** [comment]
When's the next release scheduled?

**Comment by sbarzowski** [comment]
There is no official schedule, but probably it will happen in a few days.

**Comment by harsimranmaan** [comment]
Thanks. I'll close this issue as it has landed on master.
