### ISSUE TITLE
Positional argument after a named argument is not allowed

### ISSUE THREAD

**Issue by igorwwwwwwwwwwwwwwwwwwww** [google/go-jsonnet#410]
I tried running go-jsonnet this against a pre-existing jsonnet codebase, and ran into a case of argument handling that is missing for parity with the c++ version.

The error:

```
RUNTIME ERROR: basic.libsonnet:565:5-14 Positional argument after a named argument is not allowed
```

Example libsonnet code:

```
  networkTrafficGraph(
    title='Node Network Utilization',
    description='Network utilization',
    sendQuery,
    legendFormat='{{ fqdn }}',
    receiveQuery,
    intervalFactor=3,
    legend_show=true
  )::
```

It's complaining about the line containing `sendQuery`. Note that callers are not actually using positional arguments, but setting the keys.

Example caller:

```
  basic.networkTrafficGraph(
    title='Single core saturation on the redis-cache fleet',
    sendQuery=|||
      ...
    |||,
    receiveQuery=|||
      ...
    |||,
    intervalFactor=2
  ),
```

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
Note: I was able to get this to compile by changing the definition to:

```
  networkTrafficGraph(
    title='Node Network Utilization',
    description='Network utilization',
    sendQuery=null,
    legendFormat='{{ fqdn }}',
    receiveQuery=null,
    intervalFactor=3,
    legend_show=true
  )::
```

But there's quite a few of them, so having parity with the c++ version would be nice.

**Comment by sbarzowski** [comment]
I think it's fixed on master, but it's not released yet. What is your version of Jsonnet?

Technically it was C++ implementation that didn't comply to the specification, but we ended up changing the spec and Go implemetation, because it can be useful and people are using that for production stuff.

Original issue: #314

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
Ah nice! Yeah, we're running go-jsonnet-0.15.0.

I think I can set the values to null on our end, but it'd be nice to get a new release with the fix, for others running into the same issue.

Thanks!
