### ISSUE TITLE
jsonnetfmt edge case

### ISSUE THREAD

**Issue by igorwwwwwwwwwwwwwwwwwwww** [google/go-jsonnet#411]
We ran into an edge case where `go-jsonnet`'s jsonnetfmt doesn't behave as in the c++ version.

Minimal test case:

```
foo(
  bar()
  ,
  baz=qux
)
```

go-jsonnet changes this to:

```
foo(
  bar()
  ,
  baz=qux
  
)
```

This creates issues for several reasons:

* It adds trailing spaces which get deleted by many editors.
* It is not idempotent, re-running `jsonnetfmt -i test.jsonnet` will cause lines to be added indefinitely.

We worked around it by changing the original code to:

```
foo(
  bar(),
  baz=qux
)
```

**Comment by sbarzowski** [comment]
Thanks for reporting.

**Comment by sbarzowski** [comment]
I have a funnier example:
```
foo(
  bar()
  /*1*/,/*3*/
  baz=qux
  /*2*/
)
```

It turns out there's a bug in the parser and commafodder is duplicated. I'll have a fix soon.
