### ISSUE TITLE
Compare and Contrast to Cue

### ISSUE THREAD

**Issue by ghostsquad** [google/go-jsonnet#419]
I'm curious about Cue (https://cue.googlesource.com/cue) and how it compares to jsonnet. It seems that jsonnet in a way, can handle similar validations and constraints via errors and asserts.

If anyone has more information, please post. 😊

**Comment by sbarzowski** [comment]
There is an issue about it in the Cue repo: https://github.com/cuelang/cue/issues/33. One note I have there is that IMO there is too much emphasis on OO features in Jsonnet there (and not enough emphasis on Jsonnet being a decent functional language).

Cue is a genuinely new approach for dealing with configuration and it's programming model is like nothing else I have seen. Jsonnet on the other hand is pretty much a textbook functional language.
