### ISSUE TITLE
ManifestJsonEx bug found.. 

### ISSUE THREAD

**Issue by ghostsquad** [google/go-jsonnet#423]
```
"title": "Availability (30d) > 99.000",
"title": "Availability (30d) \u003e 99.000",
```

I just discovered this when running the new go-jsonnet against kube-prometheus

@sbarzowski sorry!

**Comment by sbarzowski** [comment]
Can you send a fix + regression test?

**Comment by ghostsquad** [comment]
ya, I'm working on it now via #424
