### ISSUE TITLE
maximum number of constructed Jsonnet handles exceeded

### ISSUE THREAD

**Issue by ramaro** [google/go-jsonnet#433]
Hi,

I have a very large project using cpp-jsonnet with Kapitan. When attempting using go-jsonnet via python c-bindings (instead of cpp-jsonnet), I keep getting max handles exceed error message:
```maximum number of constructed Jsonnet handles exceeded ```

However, having manually updated this value (to a finger in the air value `const maxID = 1000000`) and recompiled go-jsonnet, the error goes away and everything works.

Not sure if the fault is at my side, but is there any chance the default number of handles can be increased? Or perhaps offer a way to specify a higher value?

**Comment by sbarzowski** [comment]
Sorry about that. We can probably get rid of the limitation (make it ~MAX_INT64).  Most probably this is a result of a native function returning a big result. Does that sound plausible?

The limit was originally introduced when the handles were used just for the VMs (and it was even smaller IIRC).

Note to self: if we raise the limit to a very big value, we may want to switch the representation to avoid the "leak".

**Comment by ramaro** [comment]
Yes, very likely happening because of a big result from a native function, but I'd have to confirm.
Making it ~MAX_INT64 sounds plausible to me. Thanks
