### ISSUE TITLE
Linter fails on unused variable when referring to a local function returning an object

### ISSUE THREAD

**Issue by freddd** [google/go-jsonnet#434]
Hi all,

We've been trying out the linter and we have quite a few places across our codebase where we have a local function returning an object. When doing this the linter fails with the message that the variable is unused, however it's definitely used. Please see the description below

A local function returning an object, taken from: https://jsonnet.org/learning/tutorial.html

Error message: `(1:1)-(17:2) Unused variable: Sour`
```
// This function returns an object. Although
// the braces look like Java or C++ they do
// not mean a statement block, they are instead
// the value being returned.
local Sour(spirit, garnish='Lemon twist') = {
  ingredients: [
    { kind: spirit, qty: 2 },
    { kind: 'Egg white', qty: 1 },
    { kind: 'Lemon Juice', qty: 1 },
    { kind: 'Simple Syrup', qty: 1 },
  ],
  garnish: garnish,
  served: 'Straight Up',
};

{
  'Whiskey Sour': Sour('Bulleit Bourbon',
                       'Orange bitters'),
  'Pisco Sour': Sour('Machu Pisco',
                     'Angostura bitters'),
}
```

**Comment by sbarzowski** [comment]
Thanks for the report. The fix for this is underway as part of a bigger linter revamp. The "new linter" does a lot more things (e.g. tries to follow the types of values and warns about incorrect usage, e.g. typos when referring to an object member).

**Comment by freddd** [comment]
@sbarzowski was the new linter merged in https://github.com/google/go-jsonnet/pull/325? If so, is there any ETA on when there will be a new release containing it?

**Comment by sbarzowski** [comment]
Yes the new linter is available on master. We don't have a set date for the next release, but it's time to cut it, so it should happen relatively soon.

In the meantime, you can build it yourself very easily (`go get github.com/google/go-jsonnet/cmd/jsonnet-lint`).
