### ISSUE TITLE
std.manifestJsonEx parameter name regression

### ISSUE THREAD

**Issue by bgagnon** [google/go-jsonnet#437]
The [documented](https://jsonnet.org/ref/stdlib.html) parameter names for `std.manifestJsonEx` are:

```jsonnet
std.manifestJsonEx(value, indent)
```

But the parameters were apparently renamed to `x` and `str` in #422.
This breaks existing code such as:

```jsonnet
std.manifestJsonEx(value={}, indent=''}
```

I think it's just this bad naming:
https://github.com/google/go-jsonnet/pull/422/files#diff-c9e72ec76c1a7488aaf4cea9ea6f1ebcR1572

```go
&binaryBuiltin{name: "manifestJsonEx", function: builtinManifestJSONEx, params: ast.Identifiers{"x", "str"}},
```

**Comment by sbarzowski** [comment]
You're 100% right. Sorry I missed that. 

Do you want to send a PR? It's enough to change the one line that you quoted.

**Comment by sbarzowski** [comment]
BTW I had a smoke test which checks all argument names for all builtin functions somewhere. I suppose I should find it and make it a part of our test suite to avoid this sort of issues in the future.
