### ISSUE TITLE
Security impact of running untrusted Jsonnet code

### ISSUE THREAD

**Issue by sh0rez** [google/go-jsonnet#446]
Executing unknown code is generally considered harmful. However, there are use-cases like playgrounds, tutorial pages, and backend services processing user input that do exactly that.

To design such a system, it's important to know how much harm can possibly happen.

Some properties of Jsonnet however make me think it's less harmful than other languages (like Go):

- Limited I/O: it can only read files and return to stdout, but not write, delete, etc.
- No network capabilities (Can't be abused to get into networks, DDOS targets, etc)
- CPU and Memory is an issue, these could be burned. Proper limits should stop this however

When running in controlled environments such as docker containers, I fail to think of a case where real harm can be done. One can use a fair amount of compute resources, but limits control this.

So, how bad can it get?

**Comment by sparkprime** [comment]
Yeah you have it right.  You should implement your own import handler to trap all I/O and sandbox it that way.  Exec it from your server in a separate process in a ulimit jail, instead of just linking the library.  That way you can bound its resource consumption and ensure that any crash does not affect other concurrent requests.  Docker isn't necessary but you could use it.

**Comment by sparkprime** [comment]
Note that this is all pretty standard -- you'd want to do the same thing even with YAML because of things like https://en.wikipedia.org/wiki/Billion_laughs_attack

**Comment by sbarzowski** [comment]
Yep, Jsonnet is easy to sandbox, but it still requires some basic setup.

I think the most important attack involving Jsonnet (which might get you pwned without you noticing) is leaking files.

if you let the user evaluate arbitrary Jsonnet and they can see the result of evaluation, is that it can be used to leak all information that importer can access (by default the whole filesystem). A sophisticated attacker doesn't even need to see the result directly – they can leak it bit by bit using timing, crashes or whatever they can control.

Using a more restrictive importer protects against it completely. This attack is most likely to happen if you don't even realize that the user can provide Jsonnet (e.g. user is supposed to provide JSON which is `import`-ed naively)
