### ISSUE TITLE
install of jsonnet-deps using GOMODULES failing

### ISSUE THREAD

**Issue by gedw99** [google/go-jsonnet#465]
any ideas ?

````

installing jsonnet

GO111MODULE="on" go get github.com/google/go-jsonnet/cmd/jsonnet
go: found github.com/google/go-jsonnet/cmd/jsonnet in github.com/google/go-jsonnet v0.16.0
which jsonnet
/Users/apple/workspace/go/bin/jsonnet
jsonnet --version
Jsonnet commandline interpreter v0.16.0

installing jsonnetfmt

GO111MODULE="on" go get github.com/google/go-jsonnet/cmd/jsonnetfmt
go: found github.com/google/go-jsonnet/cmd/jsonnetfmt in github.com/google/go-jsonnet v0.16.0
jsonnetfmt --version
Jsonnet reformatter v0.16.0

installing jsonnet-deps

GO111MODULE="on" go get github.com/google/go-jsonnet/cmd/
go get github.com/google/go-jsonnet/cmd: module github.com/google/go-jsonnet@upgrade found (v0.16.0), but does not contain package github.com/google/go-jsonnet/cmd
make: *** [this-build] Error 1
````

**Comment by sh0rez** [comment]
Where do these instructions come from? What are you trying to install?

**Comment by sbarzowski** [comment]
The last command is weird: `GO111MODULE="on" go get github.com/google/go-jsonnet/cmd/`.

It doesn't make sense to install `go get github.com/google/go-jsonnet/cmd/`. You probably wanted `GO111MODULE="on" go get github.com/google/go-jsonnet/cmd/jsonnet-deps` based on the context.

**Comment by gedw99** [comment]
True - thanks for the catch @sbarzowski . Was tired.

But i still cant get a clean install. Need it so that tools.go and go mod are happy and my build is versioned and deterministic

````
# 1
go install github.com/google/go-jsonnet/cmd/jsonnet-deps
go: finding module for package github.com/google/go-jsonnet/cmd/jsonnet-deps
module github.com/google/go-jsonnet@latest found (v0.16.0), but does not contain package github.com/google/go-jsonnet/cmd/jsonnet-deps

# 2
GO111MODULE="on" go get github.com/google/go-jsonnet/cmd/jsonnet-deps
go get github.com/google/go-jsonnet/cmd/jsonnet-deps: module github.com/google/go-jsonnet@upgrade found (v0.16.0), but does not contain package github.com/google/go-jsonnet/cmd/jsonnet-deps
make: *** [this-build] Error 1

# 3
go get -u -v github.com/google/go-jsonnet/cmd/jsonnet-deps
go get github.com/google/go-jsonnet/cmd/jsonnet-deps: module github.com/google/go-jsonnet@upgrade found (v0.16.0), but does not contain package github.com/google/go-jsonnet/cmd/jsonnet-deps
make: *** [this-build] Error 1
````

Cant think of another way to not error out...

**Comment by sbarzowski** [comment]
Ah, that's right. You're installing v0.16.0 which doesn't have jsonnet-deps yet. Your go.mod probably specifies that the version of Jsonnet is v0.16.0, so all your commands try that version.

You can try getting the newest version of modify your script, not to depend on jsonnet-deps.

**Comment by gedw99** [comment]
thankyou @sbarzowski 

That helped. had to learn the ways of go mod and now it works great !

am doing

GO111MODULE="on" go get github.com/google/go-jsonnet/cmd/jsonnet-lint@6967a297218e9fda789ae8352e09c3316c292aa4

then add the dep to the tools.go
