### ISSUE TITLE
Release 0.16.1 / 0.17.0 ?

### ISSUE THREAD

**Issue by bgagnon** [google/go-jsonnet#468]
The latest release, 0.16, is from May 22 2020. Several useful enhancements have been added since then, particularly the order-of-magnitude performance boost for JSON manifestation.

When can we expect a new tag, 0.16.1 or 0.17.0? Does it need to happen in lockstep with cpp-jsonnet?

**Comment by sbarzowski** [comment]
The new 0.17.0 release is coming relatively soon. I want to fix some stack trace issues before (I'm opposed to release waiting for features, but bugs are a different story). We always release Go and C++ versions together (there are ideas for decoupling language/library versions and interpreter performance improvements etc., but it's unclear if added complexity is worth it).

Sidenote: The releases currently require quite a lot of effort, so there is a trade-off between release frequency and development. Effectively we have releases 2-4 times a year. That's not ideal, but at this time I can only encourage everyone who needs the newest features to use the newest version from Github (or pin a specific commit).

**Comment by sbarzowski** [comment]
Release v0.17.0 is out.
