### ISSUE TITLE
linter: Linter finding issues regarding std library usage

### ISSUE THREAD

**Issue by kakkoyun** [google/go-jsonnet#483]
[While integrating the `jsonnet-linter` to our CI pipeline](https://github.com/thanos-io/kube-thanos/pull/177) I discovered issues regarding standard library functions. The linter seems like it doesn't know about the `std`. Is there a workaround for this? Or is it an issue?

```jsonnet
./jsonnet/kube-thanos/kube-thanos-query-frontend.libsonnet:57:8-64 Operand is not a boolean, it is assumed to be an array

    if !std.setMember(labelName, ['app.kubernetes.io/version'])


Problems found!
./jsonnet/kube-thanos/kube-thanos-receive-hashrings.libsonnet:19:10-21 Indexed object has no field "isArray"

  assert std.isArray(config.hashrings) : 'thanos receive hashrings has to be an array';


./jsonnet/kube-thanos/kube-thanos-receive-hashrings.libsonnet:19:10-39 Called value must be a function, but it is assumed to be void

  assert std.isArray(config.hashrings) : 'thanos receive hashrings has to be an array';


Problems found!
./jsonnet/kube-thanos/kube-thanos-store-shards.libsonnet:16:10-22 Indexed object has no field "isNumber"

  assert std.isNumber(config.shards) && config.shards >= 0 : 'thanos store shards has to be number >= 0';
```

**Comment by sbarzowski** [comment]
Thanks for reporting and sorry about this. The linter is newly released, so some rough edges like this are likely. I will fix it asap and it should get better and better over time. 

So:
1) With setMember we incorrectly assume the return type to be array, so it complains about the usage.
2) I missed `isSomething` family of functions in stdlib defintions.

We have tests for testing all combinations of argument to stdlib functions, but not for testing the assumed results. We should probably add something (although it's a bit more tricky).

BTW here is the definition of expected stdlib types: https://github.com/google/go-jsonnet/blob/v0.17.0/linter/internal/types/stdlib.go#L23.

**Comment by gotwarlost** [comment]
FYI, it is also not finding the new `std.objectValues` function added in v1.17

I'm loving the linter so far. Can't wait to use it in our projects.
