### ISSUE TITLE
Keeping files open for too long in `-m` mode – open X.json: too many open files

### ISSUE THREAD

**Issue by tvi** [google/go-jsonnet#485]
Hello,
Thanks for such a wonderful tool. I have been using this for years.
I am using go-jsonnet to write out a couple 100s (~300) of files at the same time using `-m -c` flags. However after certain threshold I get  `too many open files` error.
Ideally the writer should be batching the writes in some smaller chunks to avoid this error.

**Comment by sbarzowski** [comment]
Thanks for reporting this. We're unnecessarily leaving the files open after we write all of them.

It can be fixed be replacing [this block for writing to a file](https://github.com/google/go-jsonnet/blob/master/cmd/jsonnet/cmd.go#L348) with a single call to `ioutil.WriteFile`.

**Comment by jacksontj** [comment]
Another alternative to fix would be to move the `f.Close()` out of a defer (https://github.com/google/go-jsonnet/blob/v0.17.0/cmd/jsonnet/cmd.go#L352) -- right now it is piling those up until the for loop is complete (presumably after it has written all files). If instead this was done at the end of the loop (or the writing pushed into another method) it would move the close to be after writing each file.

**Comment by sbarzowski** [comment]
@jacksontj Yes, you are correct, but we would need to add it for both success and failure cases after WriteString. So given the chance to simplify the code or to complicate it, we should go with the former :smile:.
