### ISSUE TITLE
Why is vm.EvaluateSnippet deprecated?

### ISSUE THREAD

**Issue by gotwarlost** [google/go-jsonnet#491]
This is used by qbec, for example, to evaluate generated code with a synthetic file name.

The recommended alternatives EvaluateFile requires me to actually write a file to the filesystem and EvaluateAnonmymousSnippet loses the filename context for relative imports.

Neither work for this use-case.

**Comment by sbarzowski** [comment]
The problem with `EvaluateSnippet` is that it uses the synthetic path for resolving relative paths. This causes some issues:
* Caching – it doesn't go through the importer, so subsequent references to the same path might actually be resolved to some other location
* Trouble with canonicalizing the provided path. We pass it directly to the importer as `importedFrom` while normally only paths produced by the importer itself would be passed back to it.
* The user of the API needs to make sure that the path format is compatible with a particular importer. This is related to the point above.
* It's counter-intuitive to allow pretending that a snippet is in some particular place in the file system, while actually it's not there.

So, the recommendation is to either:
(a) make it really available at the given path
(b) treat it is as completely anonymous, without any real location (appropriate e.g. for CLI arguments) and use the paths relative to the default path of the importer.

Let me know if that answers your question.

**Comment by gotwarlost** [comment]
OK, I went through the eval code in qbec that has gone through multiple iterations in how the component jsonnet code is evaluated. It creates some synthetic functions to load non-jsonnet components (like an index.yaml file that statically defines everything). Having now revisited this code, I'm pretty sure I can process these components using the equivalent go code that is used via a native func (parseYaml for instance) in the syynthesized code and eval only the jsonnet files using evaluateFile instead of needing evaluateSnippet.

I will convert this stuff to using evaluateFile _soon_.
