### ISSUE TITLE
Support "Pretty Yaml"

### ISSUE THREAD

**Issue by ghostsquad** [google/go-jsonnet#505]
followup to #450 

This is an official request to support pretty yaml.

The primary use case is to diffing yaml easier against yaml that's written without quoting keys.

**Comment by sbarzowski** [comment]
This is much more tricky than it sounds, as explained in https://github.com/google/jsonnet/issues/821. We're open to 3rd party contributions, but it will require extensive testing and explanations why the logic is valid in all cases.

For the use case of diffing YAMLs I think a specialized tool like https://github.com/homeport/dyff or https://github.com/sahilm/yamldiff might be a better solution. This should completely eliminate the problem of having superficially different formatting. I haven't tried them, though.

**Comment by sbarzowski** [comment]
This actually happened (thanks to a great effort by @partcyborg). The support will come to go-jsonnet when we sync stdlib (before the next release).
