### ISSUE TITLE
question on TLA variables

### ISSUE THREAD

**Issue by gotwarlost** [google/go-jsonnet#510]
I want to clarify the behavior of jsonnet when TLA variables are passed in on the command line.

If the file exports a function(foo) and I pass in -A bar=baz it will complain saying that:

RUNTIME ERROR: function has no parameter bar
This is correct.

However, if the file doesn't export a function at all and is a "regular" jsonnet file exporting an object, I can pass in whatever I want as a top-level variable without complaints. Isn't this fundamentally the same issue as the one tracked in the previous error?

**Comment by sbarzowski** [comment]
You're right and I agree that it's a bit inconsistent. The way it works is that top level arguments are used at all only when the code evaluates to a function. https://github.com/google/go-jsonnet/blob/v0.17.0/interpreter.go#L1227.
