### ISSUE TITLE
std.manifestJsonEx breaking change in master

### ISSUE THREAD

**Issue by squat** [google/go-jsonnet#515]
Hi :wave: In previos versions of go-jsonnet, up to and including v0.17.0, `std.manifestJsonEx` accepted an array for the `value` parameter. As of master, passing an array causes jsonnet to throw an error a la:

```
RUNTIME ERROR: Unexpected type array, expected object
```

This seems like a breaking change in the standard library, however I could not find any references to this in the commits between the v0.17.0 tag and tip of master or any release notes. Is this known and expected behavior? If so, it would be great to have this documented somewhere so that users can expect to migrate their code.

**Comment by squat** [comment]
I bisected the changes and it seems that 7d3bda3911b71dac3d90607b5ec39a12f057640a introduces this behavior

**Comment by sbarzowski** [comment]
This is a serious bug. I should have noticed this and I'm a bit surprised that our tests didn't catch this. Many thanks for reporting this! 

The fix is probably trivial. It looks like it's enough to pass the value from `arguments[0]` directly to `aux` instead of forcing it to be an object.

**Comment by squat** [comment]
yes, that seems like an easy workaround :+1: happy to make a PR and add a test

**Comment by sbarzowski** [comment]
Great! Please go ahead.
