### ISSUE TITLE
Option to use pre-built jsonnet binary as toolchain

### ISSUE THREAD

**Issue by ashi009** [google/go-jsonnet#522]
Instead of building jsonnet as a dependency, it would be nice to provide an option to download a prebuilt binary instead. So that the jsonnet deps don't have to be managed by the end-users (which is problematic until bzlmod is landed.)

**Comment by sbarzowski** [comment]
There is an option to do that (but only for official releases). See e.g.: https://github.com/google/go-jsonnet/releases/tag/v0.17.0

Let me know if there is any problem with that.
