### ISSUE TITLE
Python bindings cannot handle passing a map to a python native function

### ISSUE THREAD

**Issue by PaulFurtado** [google/go-jsonnet#526]
It looks like the Python bindings cannot handle passing a map to a native callback.

Here's a 1-liner passing an int to a native callback that works correctly:
```python
_gojsonnet.evaluate_snippet("test", "std.native('myfunc')(1)", native_callbacks={"myfunc": (("x",), lambda x: x)}
```
this returns:
```python
"1\n"
```

However, if you pass a map instead of an integer like:
```python
_gojsonnet.evaluate_snippet("test", "std.native('myfunc')({a:1})", native_callbacks={"myfunc": (("x",), lambda x: x)}
```
it results in:
```
RuntimeError: RUNTIME ERROR: failed to execute native callback, code: 0
	test:1:1-28	$
	During evaluation
```

**Comment by PaulFurtado** [comment]
I'm actually realizing that the native jsonnet python bindings didn't support this either. We're hitting a bug in our migration from the native bindings to the gojsonnet bindings, and I thought this was the issue but I misread our code. Something else is going on here that I'll try to track down and post a different issue for.  Sorry for the noise!

**Comment by sbarzowski** [comment]
Sure. Please don't hesitate if you find something we should take a look at.
