### ISSUE TITLE
Lazy evaluation not late enough?

### ISSUE THREAD

**Issue by aug0stus** [google/go-jsonnet#535]
Hello all,

A while ago, I experienced an odd behavior when dealing with an object composition operation. I stripped the code to a bare example to demonstrate.

```jsonnet
// main.libsonnet 
{
  local main = self,

  name:: 'main',

  main: {
    properties: main._config,
  },

  _config+:: {
    name: main.name,
  },
}
```

```jsonnet
// mixed.jsonnet 
local o = import 'main.libsonnet';

o {
  name:: 'mixed',

  mixed: {
    properties: o._config,
  },
}
```

The output of `mixed.jsonnet` is the following, 
```json
{
   "main": {
      "properties": {
         "name": "mixed"
      }
   },
   "mixed": {
      "properties": {
         "name": "main"
      }
   }
}
```

Because `name:: 'mixed'` is the right hand side object, I expected that to override `name:: 'main'` , and the lazy evaluations to happen only *after* that's done. 

What I see happening instead though, is that part of right hand side object is already fully evaluated before the override of `name:: 'mixed'` occurs. Could this be a bug, or maybe I am simply just being too experimental ?

_Side Note_: For my actual use case, I ended up using a workaround which involved something like a `std.strReplace(<str>, $['name'], "mixed")` to patch a string that was being formatted with `$['name']`.

**Comment by seh** [comment]
One workaround in file _mixed.jsonnet_:
```jsonnet
o {
  name:: 'mixed',

  local top = self,

  mixed: {
    properties: top._config,
  },
}
```

**Comment by sbarzowski** [comment]
@seh That is correct. It's the right way to achieve the goal.

@aug0stus Your example works as expected. Let me explain why.

```
local o = {
  local main = self,

  name:: 'main',

  main: {
    properties: main._config,
  },

  _config+:: {
    name: main.name,
  },
};

o {
  name:: 'mixed',

  mixed: {
    properties: o._config,  // <---------------------- Look here!
  },
}
```

When you're referring to `o._config` you're referring to the original object `o` with fixed field values, not to the current object which can have overridden values. If you want to refer to the current object you have to use `self` instead of `o` like in @seh's example

For more insight, you can read https://jsonnet.org/ref/language.html#inheritance and https://jsonnet.org/ref/language.html#self-referencing-objects. The most relevant part is the distinction between using self and indexing from outside.

**Comment by aug0stus** [comment]
Ah I understand now. Thanks ! 

I did go over the documentation when I first started using the language, but I admit that I did skimp over many of the languages' nuances at the time. It's been insightful to go over the references once more with more experience this time. 

I used `$` instead of `o`, which is similar to the recommendations of @seh, and got the desired results.

``` jsonnet
local o = {
  local main = self,

  name:: 'main',

  main: {
    properties: main._config,
  },

  _config+:: {
    name: main.name,
  },
};

o {
  name:: 'mixed',

  mixed: {
    properties: $._config,  // <---------------------- Look here!
  },
}
```

**Comment by sbarzowski** [comment]
Glad it helped. Please note that the semantics of your final version are still different from what seh proposed. This is a common confusion, so let me clarify.

Your version is equivalent to the following:
```
local o = {
  local main = self,

  name:: 'main',

  main: {
    properties: main._config,
  },

  _config+:: {
    name: main.name,
  },
};

local o2 = o {  // <--------------- introducing a name for the second object
  name:: 'mixed',

  mixed: {
    properties: o2._config,  // <---------------------- Look here!
  },
};

o2
```

The expression `$` is a shortcut for the lexically outermost object and can always be replaced with an explicit `local`. So in this case you're getting an object which is recursively defined, but `$._config` still refers to a fixed value like in the original example. You can see the difference if you add yet another object on top.

Here's an example which illustrates the difference:

```
local o = {
  local main = self,

  name:: 'main',

  main: {
    properties: main._config,
  },

  _config+:: {
    name: main.name,
  },
};

local o_middle_dollar = o {
  name:: 'middle-dollar',

  mixed: {
    properties: o_middle_dollar._config,  // <---------------------- Recursive definition
  },
};

local o_middle_self = o {
  local top = self,
  name:: 'middle-self',

  
  mixed: {
   properties: top._config,  // <---------------------- Using self
  }
};

[
    o_middle_dollar + { name:: "final" },
    o_middle_self + { name:: "final" },
]
```

Resulting in:

```
[
  {
    "main": {
      "properties": {
        "name": "final" // main.properties.name evaluates through self, so it's updated
      }
    },
    "mixed": {
      "properties": {
        "name": "middle-dollar" // This is just defined in terms of `o_middle_dollar`.
      }
    }
  },
  {
    "main": {
      "properties": {
        "name": "final" // Same as in the first object.
      }
    },
    "mixed": {
      "properties": {
        "name": "final" // Here it is also defined through self.
      }
    }
  }
]
```

Both behaviors are useful depending on what you're trying to do. See also: https://jsonnet.org/ref/language.html#self-referencing-objects

**Comment by aug0stus** [comment]
Thanks a ton for correcting me and for the informational demonstration, I think I have a better much better understanding of the complexities involving `self`, `$` and `super` now.

:)
