### ISSUE TITLE
jsonnet-lint doesn't handle the super keyword correctly

### ISSUE THREAD

**Issue by gotwarlost** [google/go-jsonnet#539]
This weekend I tried to incorporate a lint command into qbec that uses jsonnet-lint as a library (needed because of qbec's custom importers etc.). I let it loose on our biggest jsonnet repo and it found a lot of valid problems and such but failed incorrectly on one file. It's come along really well.

This is the repro test case.

```
$ cat x.jsonnet
local foo = { config: [{ x: 'y' }] };
foo {
  config: [super.config[0] { a: 'b' }],
}

$ jsonnet x.jsonnet
{
   "config": [
      {
         "a": "b",
         "x": "y"
      }
   ]
}

$ jsonnet-lint x.jsonnet
x.jsonnet:3:12-27 Indexed value is assumed to be an object, but index is not a string

  config: [super.config[0] { a: 'b' }],


Problems found!

```

**Comment by sbarzowski** [comment]
Reproduced on my end. Not sure why this is happening. I verified that it in fact thinks that `super.config` must be an object, which is of course wrong (so the issue is with type inference, not with checking logic).

I will update when I know more.

**Comment by sbarzowski** [comment]
Ok, it was just a bad hardcoded value. We don't really do anything smart about `super.something` (it can potentially be anything).

**Comment by gotwarlost** [comment]
wow, that fix was wicked fast! Confirmed that the latest commit works. Thanks a bunch
