### ISSUE TITLE
pre-commit hook failed when committing multiple jsonnet files

### ISSUE THREAD

**Issue by thombashi** [google/go-jsonnet#543]
[pre-commit hook of jsonnet-lint](https://github.com/google/go-jsonnet/blob/46d1fceb9c77c6494007c69a164ce3566b28e990/.pre-commit-hooks.yaml#L9-L15) failed when passing multiple jsonnet files.

```
$ pre-commit run --files a.jsonnet b.jsonnet
jsonnetfmt...............................................................Passed
jsonnet-lint.............................................................Failed
- hook id: jsonnet-lint
- exit code: 1

ERROR: only one file is allowed
```

Therefore, if you install the pre-commit hook, commits that involve changes to multiple jsonnet files will fail.
This is a little bit inconvenient for development.

Is there any reason to `jsonnet-lint` accept only one file?
May I open a pull request to change to accept multiple jsonnet files?

**Comment by sbarzowski** [comment]
> Is there any reason to jsonnet-lint accept only one file?

No there isn't. I just haven't got to it yet.

> May I open a pull request to change to accept multiple jsonnet files?

That would be great.

Doing it properly means passing multiple files here: https://github.com/google/go-jsonnet/blob/v0.17.0/linter/linter.go#L42
and adding them all to roots: https://github.com/google/go-jsonnet/blob/v0.17.0/linter/linter.go#L44 and subsequently processing them all. It's especially important to go over them all together here: https://github.com/google/go-jsonnet/blob/v0.17.0/linter/internal/types/check.go#L136. This way we avoid processing common dependencies multiple times during type checking.

If you don't have time for implementing the full solution, I would also be happy to accept the updated to the CLI which just calls linter on each file in a loop with an appropriate TODO. It's not as efficient, but it's still a step in the right direction.

**Comment by thombashi** [comment]
@sbarzowski 
Thank you for your comment and implementation advice.

I had tried to implement the full solution that you mentioned.
Please check that out.
