### ISSUE TITLE
Missing jsonnet_realloc and other C bindings

### ISSUE THREAD

**Issue by knoepfel** [google/go-jsonnet#562]
It appears that PR #466 was intended to bring the C bindings in line with the `jsonnet` C API.  However, after building the most recent `go-jsonnet` C-bindings (using `go build -buildmode=c-shared -o libjsonnet.so`), the following functions are not exported *even though* their symbols are included in the shared object library:

- `jsonnet_gc_growth_trigger`
- `jsonnet_gc_min_objects`
- `jsonnet_realloc`

Are these omissions intentional?  We do see mention of `jsonnet_realloc` at https://github.com/google/go-jsonnet/pull/466#issuecomment-731599360.  Our hope was to use the `go-jsonnet` C bindings as a drop-in replacement for the `jsonnet` C API.  However, we cannot do so because of these missing functions.

It is trivial for us to patch the `libjsonnet.h` file to include the appropriate function declarations, but we did not want to do so until we understood better what the situation was.

**Comment by mikehoyle-google** [comment]
It's been (interestingly) exactly a year later, but I'll add to this thread. I have built the c-bindings as a dll for windows and can confirm no realloc/free function is exported.

```
> cd .\c-bindings
> go build -o libjsonnet.dll -buildmode=c-shared
```

When I use the DLL Export Viewer utility, it reveals everything that's been exported as a callable endpoint in the library.
https://gist.github.com/mikehoyle-google/57159bff7c218b33e600b384882483a6

You can see there is no jsonnet_realloc there. That's further reinfoced by looking at the generated header, also included in the gist above.

**Comment by sparkprime** [comment]
The declaration of jsonnet_realloc doesn't get generated into the libgojsonnet.h file, because it's not in the c-bindings.go file...  I'm not sure how to fix that yet.

**Comment by sparkprime** [comment]
I think the declaration just needs to be added to `internal.h` (and probably we can take out the "jsonnet_internal_free_string" one from there.

**Comment by sparkprime** [comment]
Awesome, thanks
