### ISSUE TITLE
Any plan for vscode plugin?

### ISSUE THREAD

**Issue by loynoir** [google/go-jsonnet#572]
### Background
https://marketplace.visualstudio.com/items?itemName=heptio.jsonnet

https://github.com/heptio/vscode-jsonnet has been archived by the owner. It is now read-only. 

https://marketplace.visualstudio.com/items?itemName=Sebbia.jsonnetng

### Issue
Both plugins using `jsonnet language server`, somehow try to import percentage encoded dependency path, instead of dependency path.

```txt
Error: ENOENT: no such file or directory, stat `path/to/%XX%YY/index.jsonnet`
```

Are there any plans for official vscode plugin?  Even lack of a good way to submit a vscode plugin issue, since repo has been archived. 😭

**Comment by sbarzowski** [comment]
We have no control.

I would love to see VS Code plugin, but I don't have capacity to create it myself. I think even a very minimal plugin (just the up-to-date syntax highlighting, working comment-out shortcuts) would be great. Less fancy stuff. but actually reliable is what we need now.

I would be very happy to answer any Jsonnet questions and help along, but someone else needs to be the driving force for the new plugin.

**Comment by loynoir** [comment]
Wow 😄
https://github.com/google/jsonnet/issues/862#issuecomment-991962795
