### ISSUE TITLE
The linter is unaware of std.isArray() and std.isObject()

### ISSUE THREAD

**Issue by wattdave** [google/go-jsonnet#574]
I've been running the linter over a file, and got this:
```text
adsk/pipelines/lb.pipeline.libsonnet:93:53-64 Indexed object has no field "isArray"

    local arrayToObjectWithValue(field, value) = if std.isArray(value) then { value: value } else value;
```
This is similar to the other issue involving std.member() that was cited earlier. I'm running 0.17.0 of jsonnet.

**Comment by sbarzowski** [comment]
Can you reproduce the issue with the newest version?

**Comment by wattdave** [comment]
That was the latest version, as of that date. The error is gone in 0.18.0, though. Thanks!
