### ISSUE TITLE
Method copied to new object stays bound to previous object

### ISSUE THREAD

**Issue by tomlinford** [google/go-jsonnet#581]
I noticed that if a method gets copied to a new object, the `self` wasn't working as expected. I'm not sure if this is expected behavior. Here's a simple reproduction of the issue:
```sh
$ jsonnet -v
Jsonnet commandline interpreter (Go implementation) v0.18.0
$ jsonnet -e 'local x = {foo(): self.bar, bar: 1}; local y = {[k]:x[k] for k in std.objectFields(x)} + {bar: 2}; y.foo()'
1
```
In `y`, the `bar` field is overwritten to be `2`, but the `self.bar` referenced in the `foo()` call returns `1` instead of the expected `2`. One can work around this issue by not copying over the functions and keeping the original object as a parent:
```sh
$ jsonnet -e 'local x = {foo(): self.bar, bar: 1}; local y = x + {[k]:x[k] for k in std.objectFields(x) if !std.isFunction(x[k])} + {bar: 2}; y.foo()'
2
```

FWIW, this is also present in the C++ implementation:
```sh
$ ./jsonnet -v
Jsonnet commandline interpreter v0.18.0
$ ./jsonnet -e 'local x = {foo(): self.bar, bar: 1}; local y = {[k]:x[k] for k in std.objectFields(x)} + {bar: 2}; y.foo()'
1
```

**Comment by sbarzowski** [comment]
It's consistent with the specification.

The `x[k]` expression refers to a field of a concrete object `x`, so `self.bar` is evaluated in the context of `x`, so it's `1`.

Consider a modified example:
```
local x = {
    foo: self.bar, bar: 1
};
local y = {
    [k]:x[k] for k in std.objectFields(x)
} + {baz: self.bar} + {bar: 2};
y
```

It evaluates to:
```
{
  "bar": 2,
  "baz": 2,
  "foo": 1
}
```

**Comment by sbarzowski** [comment]
(Feel free to reopen if you have it's unclear.)

**Comment by tomlinford** [comment]
Hi @sbarzowski thanks for the reply. I'm not sure if your example captured what I was getting at. Your example makes sense since `x.foo` would've been immediately set, but if `x.foo` were a method, I'd expect it to be evaluated lazily:
```jsonnet
local x = {foo(): self.bar, bar:1};
local y = x {bar: 2};
y.foo()
```
^ This gives `2`, as expected

But now suppose we do `y = {foo: x.foo, bar: 2}` instead of object composition. I'd expect that the "code" of the foo method to get copied over and for the result to be equivalent:
```jsonnet
local x = {foo(): self.bar, bar:1};
local y = {foo: x.foo, bar: 2};
y.foo()
```
But this gives `1`, which I did not expect.

**Comment by sbarzowski** [comment]
I see. Your mental model does not match actual semantics.

Whether `x.foo` is a method or not is irrelevant. All fields are evaluated lazily, regardless of whether they are methods. Methods in Jsonnet are just fields with function values.

Whenever you're accessing the object fields "from outside" (i.e. not through `self` or `super`) it gets evaluated in the context of the referenced object. In particular, `x.foo` is evaluated to a 0-argument function. The `self` gets fixed to `x`. This is a function in the mathematical sense, there is no hidden dependency on `self` anymore.

You might want to take a look at these part of the language reference.
* https://jsonnet.org/ref/language.html#inheritance
* https://jsonnet.org/ref/language.html#self-referencing-objects

Let me know if you have more questions.

**Comment by tomlinford** [comment]
Ahh that makes sense -- for some reason I was thinking about this from the perspective of these being types rather than instances of types. This then matches with what I'd expect from a language like python:
```
>>> class A:
...   def foo(self): return self.bar
...   bar = 1
...
>>> class B:
...   bar = 2
...
>>> b = B()
>>> b.foo = A().foo
>>> b.foo()
1
```

Thanks!
