### ISSUE TITLE
How to create your own `myStd`?

### ISSUE THREAD

**Issue by jordan-da** [google/go-jsonnet#598]
Looking for guidance on how to create a `vm` with my own `std` _like_ symbol stuffed with `NativeFunction`s and variables. I do understand that I can use things like `std.native` to accomplish this, but I was really hoping to make this a first class thing within the context of the pre-rendered jsonnet.

So far the best I can come up with is creating a snippet similar to

https://github.com/kapicorp/kapitan/blob/master/kapitan/lib/kapitan.libjsonnet

and then manually modifying the incoming snippet to include something like:
```jsonnet
local myStd = {
    myFunc1(a, b):: std.native("my_crazy_func_1")(a, b),
    myFunc2(a, b):: std.native("my_crazy_func_2")(a, b),
    myFunc3(a, b):: std.native("my_crazy_func_3")(a, b),
}
```
...but this feels a little gross to me. I feel like there should be a better way but I can't seem to figure it out by looking at the code. I guess what I am asking for is a way to include ye-mighty-block of my own builtins, not unlink you do here
https://github.com/google/go-jsonnet/blob/9e9321f69ae1554de722f2a478f3fbca240f862a/builtins.go#L1616-L1669

Thanks in advance!

**Comment by sbarzowski** [comment]
Native functions + a wrapper are currently the official way of adding your own native code. 

Not sure how the ideal solution would look like for you.

**Comment by CertainLach** [comment]
In jrsonnet, I provide api for adding globals, and builtins are plain functions, so user can construct custom library object, and then add it to vm:
https://github.com/CertainLach/deppatcher/blob/master/src/main.rs#L367-L374

**Comment by sbarzowski** [comment]
I don't see anything actionable here. Closing, but feel free to reopen.
