### ISSUE TITLE
std.substr returns \0 padding in case of multibyte characters present 

### ISSUE THREAD

**Issue by CertainLach** [google/go-jsonnet#600]
Running `std.substr("🤩", 0, 5)`

Returns `"🤩\u0000\u0000\u0000"`

I think issue is using `len()` on string, not on rune array here?
https://github.com/google/go-jsonnet/blob/master/builtins.go#L1022-L1024

"🤩" is 4 bytes, but only one rune, so end index should be bounded to 1 here

**Comment by sbarzowski** [comment]
You're correct, thanks for catching this.
