### ISSUE TITLE
linter: std function unrecognized; skip lint directive?

### ISSUE THREAD

**Issue by bwplotka** [google/go-jsonnet#610]
Hi, 

I think there is some linter problem with `std.manifestJsonMinified` function.

Code like:

```
local objects = [{ test: '' }, { bar: 'filter2' }, { bar: 'filter' }, { foo: '' }];

{
  spec: std.sort(objects, std.manifestJsonMinified),
}
```

Fails the lint with:

```
test.jsonnet:4:27-51 Indexed object has no field "manifestJsonMinified"

  spec: std.sort(objects, std.manifestJsonMinified),
```

Blocking: https://github.com/rhobs/configuration/pull/227

On a separate note, is there a way to add some directive that skips false positives?

**Comment by sbarzowski** [comment]
> On a separate note, is there a way to add some directive that skips false positives? 

You mean like for a single line? That would be very useful, but we don't have that yet.

**Comment by jaymebrd** [comment]
@bwplotka @sbarzowski I put up a PR to fix the linter issue

**Comment by sbarzowski** [comment]
The PR was merged. Thanks a lot!
