### ISSUE TITLE
Release a new version now that the x/sys package has been upgraded

### ISSUE THREAD

**Issue by george-e-shaw-iv** [google/go-jsonnet#611]
Please release this now that the x/sys package has been upgraded to get rid of the errors when running this tool with 1.18 - https://github.com/google/go-jsonnet/commit/7032dd729f7e684dcfb2574f4fe99499165ef9cb

**Comment by dan-aksenov** [comment]
Is there any chance to get this updated?

**Comment by sparkprime** [comment]
Yeah I can do it later this week

**Comment by Moulick** [comment]
@sparkprime any hope of this weekend?

**Comment by Moulick** [comment]
Made a pull request https://github.com/google/go-jsonnet/pull/623 for the change

**Comment by Moulick** [comment]
umm, why the reopen @sbarzowski ? Did the PR miss something?

**Comment by sbarzowski** [comment]
I think the request here is to release a new version of Jsonnet.

**Comment by george-e-shaw-iv** [comment]
That is definitely the request, to please release a new version of jsonnet.

**Comment by cannonpalms** [comment]
Where are we on this new release @sbarzowski ?

**Comment by sparkprime** [comment]
I'm planning to do it, we have a process where we ensure everything is in sync between the two versions and all the tests work on all the platforms, so it's not completely trivial.  @sbarzowski anything we want to get in first?

**Comment by sparkprime** [comment]
Now https://github.com/google/go-jsonnet/issues/562 is sorted I'll do it

**Comment by Moulick** [comment]
https://github.com/Homebrew/homebrew-core/pull/114070
