### ISSUE TITLE
Asserted variable considered unused

### ISSUE THREAD

**Issue by FUSAKLA** [google/go-jsonnet#617]
Hi, I just bumped into an issue when using 
```jsonnet
{   
    local input = [1,2,3],
    local knownItems = [1,2],
    local unknownItems = std.filter(function(i) !(i in knownItems), input),
    assert unknownItems == [] : "unexpected items: %s" % std.join(",",unknownItems)
}
```
Linter returns
```
Unused variable: unknownItems
```

Usage of the local variable here is obvious to avoid duplication of the filtering, but it is used just for assertion and validation of input data.

Would it be possible to also reflect usage in assertion?

**Comment by sparkprime** [comment]
yes this is a bug in the linter
