### ISSUE TITLE
linter missing `std.get()`

### ISSUE THREAD

**Issue by drewhutchison** [google/go-jsonnet#626]
built from #cb3a759, with test file containing `std.get({}, 'dummy', 'default')`:

`jsonnet` returns `"default"`, however `jsonnet-lint` returns:

```
test.jsonnet:1:1-8 Indexed object has no field "get"

std.get({}, 'dummy', 'default')


test.jsonnet:1:1-32 Called value must be a function, but it is assumed to be void

std.get({}, 'dummy', 'default')


Problems found!
```

`std.get` available since v0.18.0 (per https://github.com/google/jsonnet/blob/b96fa6c1ea2a142d526296f8b29c1b39b0075fd5/doc/ref/stdlib.html#L160) however appears to be missing from `linter/internal/types/stdlib.go`.

**Comment by sbarzowski** [comment]
Yep, needs to be added there.
