### ISSUE TITLE
std.member does not handle strings correctly

### ISSUE THREAD

**Issue by smcgivern** [google/go-jsonnet#656]
Regular jsonnet defines `std.member` on strings in terms of `std.findSubstr`: https://github.com/google/jsonnet/blob/813c7412d1c7a42737724d011618d0fd7865bc69/stdlib/std.jsonnet#L236-L241

This means that if the first argument is a string, the second argument can be a string of any length.

The native version added in https://github.com/google/go-jsonnet/pull/638 only allows the second argument to be a single-character string. That is, with this input:

```jsonnet
{
  'foo': std.member('foobar', 'foo'),
}
```

`go-jsonnet` 0.18.0 returns:

```json
{
   "foo": true
}
```

But 0.19 and later returns:

```json
{
   "foo": false
}
```

Doing `std.member('foobar', 'o')` will return `true`, however.

**Comment by salvacorts** [comment]
I just opened a PR fixing this: https://github.com/google/go-jsonnet/pull/657

**Comment by smcgivern** [comment]
Thanks!

**Comment by anguslees** [comment]
Request: can we get a 0.19.x, containing this fix?

It's subtle, is a regression, and yet silently does the wrong thing.  I just lost a few hours to debugging something that turned out to be this.

**Comment by sparkprime** [comment]
Yes this makes sense and we should have done a release much earlier
