### ISSUE TITLE
`jsonnet-lint` / `jsonnet-deps` hangs on importing `stdin`

### ISSUE THREAD

**Issue by davidreuss** [google/go-jsonnet#668]
👋 

Currently `jsonnet-lint` and `jsonnet-deps` hangs on a file that tries to import stdin:

```
import '/dev/stdin'
```

I'm not entirely sure what the appropriate fix would be here, but it looks like it may need to be determined in a [couple of places](https://github.com/google/go-jsonnet/blob/b38dfbb86e984449f7bc15048b467ced56501430/linter/linter.go#L103), and i'm not really sure this is the correct place for the fix.

If you give me pointers on how you'd want to potentially fix this, i'd be happy to take a look at getting it done.

for context, this problem showed up when using https://github.com/grafana/jsonnet-language-server (filed https://github.com/grafana/jsonnet-language-server/issues/87 for reference there) -- which we saw weird strange lint results on some of our projects, and then found out about deeply buried imports of stdin the be the cause, so naturally we get linting errors on files which end up importing that deeply rooted library, which has a conditional import of stdin.

Thanks in advance.

**Comment by anguslees** [comment]
Do you have minimal test case?

From some quick tests[1], I can't reproduce this, and I _suspect_ the issue is that you're not providing a finite-length stdin when you run `jsonnet-lint`, but you are when you run regular `jsonnet`.

If this is your issue, adding `< /dev/null` (or similar) to your `jsonnet-lint` invocation should allow `import "/dev/stdin"` to read until end-of-file and proceed with the rest of your jsonnet code in a timely fashion.

---

[1] My quick tests:
```console
% echo 'import "/dev/stdin"' > stdin.jsonnet
% echo 40 + 2 | jsonnet stdin.jsonnet
42
% echo 40 + 2 | jsonnet-lint stdin.jsonnet
(exits successfully, quickly)

% echo 'importstr "/dev/stdin"' > stdinstr.jsonnet
% echo 40 + 2 | jsonnet stdinstr.jsonnet
"40 + 2\n"
% echo 40 + 2 | jsonnet-lint stdinstr.jsonnet
(exits successfully, quickly)
```

**Comment by anguslees** [comment]
From a quick skim of the jsonnet-language-server code, I see it's invoking lint or eval functions directly (in process).  This means `import "/dev/stdin"` is reading the 'real' stdin of the language server process, which is exciting.

I don't have much experience with jsonnet-language-server - if it doesn't use stdin for anything else, I suggest you run jsonnet-language-server with `< /dev/null`.  If that works, it's probably worth a bug to that project to suggest either closing stdin (fd 0) somewhere during startup, or provide a custom jsonnet importer that tries to avoid situations like this (read with a timeout, or reject certain paths like "/dev/stdin", or reject all non-regular file types).

**Comment by davidreuss** [comment]
>This means import "/dev/stdin" is reading the 'real' stdin of the language server process, which is exciting.

😂 

Workarounds for `jsonnet-lint` seems to work, so i don't think this warrants any change in this repository. 👍 

I'll try and poke at a few things to see if i can get the language server to work under these circumstances ... otherwise, some local shim library are probably the way forward, `import "/dev/stdin"` is an anti pattern anyways, and `tla` args should probably be preferred in the vast majority of cases.

Thanks for the insights 💯
