### ISSUE TITLE
Is `v0.20.0` the latest release?

### ISSUE THREAD

**Issue by ZhongRuoyu** [google/go-jsonnet#690]
Hi! [Homebrew](https://github.com/Homebrew/brew) maintainer here. We noticed that `v0.20.0` was tagged, but is not yet marked as latest on the repo's [releases page](https://github.com/google/go-jsonnet/releases). I'm filing this issue to confirm if the release is ready to be marked as latest, so that we can go ahead and ship it. Thanks!

**Comment by sparkprime** [comment]
I added the latest flag, thanks for the heads up

**Comment by ZhongRuoyu** [comment]
Thanks @sparkprime! We'll ship the 0.20.0 release.
