### ISSUE TITLE
`--jpath` does not support multiple search paths

### ISSUE THREAD

**Issue by skuzzle** [google/go-jsonnet#744]
Hi,

I was surprised by this behavior, also the console help text is not very precise regarding whether multiple search paths are even allowed or not.

Given the following directory structure:
```
project/
├─ vendor1/
│  ├─ lib1/
│  │  ├─ shared1.txt    // content: "shared1"
├─ vendor2/
│  ├─ lib2/
│  │  ├─ shared2.txt    // content: "shared2"
```

Passing multiple library directories via `JSONNET_PATH` seems to work as expected, properly resolving files from both library locations:
```
JSONNET_PATH=$(pwd)/vendor1:$(pwd)/vendor2 jsonnet -e "(importstr 'lib1/shared1.txt')+(importstr 'lib2/shared2.txt')"

> "shared1shared2"
```

However, the same with the `-J` or `--jpath` argument does not work:
```
jsonnet --jpath $(pwd)/vendor1:$(pwd)/vendor2 -e "(importstr 'lib1/shared1.txt')+(importstr 'lib2/shared2.txt')" 

RUNTIME ERROR: couldn't open import "lib1/shared1.txt": no match locally or in the Jsonnet library paths
	<cmdline>:1:2-30	$
	During evaluation	
```

Tested with
```
jsonnet -version

> Jsonnet commandline interpreter (Go implementation) v0.20.0
```

Quick reproducer project with the example from above can be found here: https://github.com/skuzzle/jpath-issue-reproducer

**Comment by zarelit** [comment]
@skuzzle you can specify the option multiple times like `jsonnet -J $(pwd)/vendor1 -J $(pwd)/vendor2`, in case the file is present in multiple directories the last one wins.

Issuing `jsonnet --help` prints an example of how `JSONNET_PATH` env variable and `-J` options interact together

> Environment variables:
  JSONNET_PATH is a colon (semicolon on Windows) separated list of directories
  added in reverse order before the paths specified by --jpath (i.e. left-most
  wins). E.g. these are equivalent:
    JSONNET_PATH=a:b jsonnet -J c -J d
    JSONNET_PATH=d:c:a:b jsonnet
    jsonnet -J b -J a -J c -J d

**Comment by zarelit** [comment]
AFAICT from the code it doesn't look like it, but I'll leave the actual answer to the devs
